INSERT IGNORE INTO stock_symbols (symbol, company_name) VALUES
('A', 'Agilent Technologies'),
('AA', 'Alcoa'),
('AAL', 'American Airlines Group'),
('AAOI', 'Applied Optoelectronics'),
('AAON', 'AAON'),
('AAP', 'Advance Auto Parts'),
('AAPL', 'Apple'),
('AARD', 'Aardvark Therapeutics'),
('AAT', 'American Assets Trust'),
('AAUC', 'Allied Gold Corporation Common Shares'),
('ABAT', 'American Battery Technology Company'),
('ABBV', 'AbbVie'),
('ABCB', 'Ameris Bancorp'),
('ABCL', 'AbCellera Biologics Inc. Common Shares'),
('ABEO', 'Abeona Therapeutics'),
('ABL', 'Abacus Global Management'),
('ABM', 'ABM Industries Incorporated'),
('ABNB', 'Airbnb'),
('ABT', 'Abbott Laboratories'),
('ABTC', 'American Bitcoin'),
('ABVX', 'Abivax SA'),
('ACAD', 'ACADIA Pharmaceuticals'),
('ACB', 'Aurora Cannabis Inc. Common Shares'),
('ACGL', 'Arch Capital Group Ltd.'),
('ACHC', 'Acadia Healthcare Company'),
('ACHR', 'Archer Aviation'),
('ACI', 'Albertsons Companies'),
('ACIW', 'ACI Worldwide Inc'),
('ACLS', 'Axcelis Technologies'),
('ACM', 'AECOM'),
('ACN', 'Accenture'),
('ACP', 'abrdn Income Credit Strategies Fund Common Shares'),
('ACT', 'Enact Holdings'),
('ACVA', 'ACV Auctions'),
('ADAM', 'Adamas Trust'),
('ADBE', 'Adobe'),
('ADC', 'Agree Realty'),
('ADEA', 'Adeia'),
('ADI', 'Analog Devices'),
('ADM', 'Archer-Daniels-Midland Company'),
('ADMA', 'ADMA Biologics Inc'),
('ADNT', 'Adient plc'),
('ADP', 'Automatic Data Processing'),
('ADPT', 'Adaptive Biotechnologies'),
('ADSK', 'Autodesk'),
('ADT', 'ADT'),
('ADTN', 'ADTRAN Holdings'),
('ADX', 'Adams Diversified Equity Fund'),
('AEE', 'Ameren'),
('AEF', 'abrdn Emerging Markets ex-China Fund'),
('AEG', 'Aegon Ltd. New York Registry Shares'),
('AEHR', 'Aehr Test Systems'),
('AEM', 'Agnico Eagle Mines Limited'),
('AEO', 'American Eagle Outfitters'),
('AEP', 'American Electric Power Company'),
('AES', 'The AES'),
('AESI', 'Atlas Energy Solutions'),
('AEVA', 'Aeva Technologies'),
('AFG', 'American Financial Group'),
('AFL', 'AFLAC Incorporated'),
('AFRM', 'Affirm Holdings'),
('AG', 'First Majestic Silver'),
('AGCO', 'AGCO'),
('AGH', 'Aureus Greenway Holdings'),
('AGI', 'Alamos Gold'),
('AGIO', 'Agios Pharmaceuticals'),
('AGNC', 'AGNC Investment'),
('AGRO', 'Adecoagro S.A. Common Shares'),
('AGYS', 'Agilysys'),
('AHCO', 'AdaptHealth'),
('AHH', 'Armada Hoffler Properties'),
('AI', 'C3.ai'),
('AIG', 'American International Group Inc. New'),
('AIOT', 'PowerFleet'),
('AIP', 'Arteris'),
('AIRO', 'AIRO Group Holdings'),
('AIRS', 'AirSculpt Technologies'),
('AIV', 'Apartment Investment and Management Company'),
('AIZ', 'Assurant'),
('AJG', 'Arthur J. Gallagher & Co.'),
('AKAM', 'Akamai Technologies'),
('AKRO', 'Akero Therapeutics'),
('AL', 'Air Lease'),
('ALAB', 'Astera Labs'),
('ALB', 'Albemarle'),
('ALC', 'Alcon'),
('ALDX', 'Aldeyra Therapeutics'),
('ALE', 'Allete'),
('ALEX', 'Alexander & Baldwin'),
('ALGM', 'Allegro MicroSystems'),
('ALGN', 'Align Technology'),
('ALGT', 'Allegiant Travel'),
('ALH', 'Alliance Laundry Holdings'),
('ALHC', 'Alignment Healthcare'),
('ALK', 'Alaska Air Group'),
('ALKS', 'Alkermes plc'),
('ALKT', 'Alkami Technology'),
('ALL', 'Allstate Corporation'),
('ALLE', 'Allegion plc'),
('ALLT', 'Allot Ltd.'),
('ALLY', 'Ally Financial'),
('ALM', 'Almonty Industries Inc. Common Shares'),
('ALNY', 'Alnylam Pharmaceuticals'),
('ALSN', 'Allison Transmission Holdings'),
('ALV', 'Autoliv'),
('AM', 'Antero Midstream'),
('AMAT', 'Applied Materials'),
('AMBA', 'Ambarella'),
('AMBC', 'Ambac Financial Group'),
('AMCR', 'Amcor'),
('AMCX', 'AMC Networks'),
('AMD', 'Advanced Micro Devices'),
('AME', 'AMETEK'),
('AMGN', 'Amgen'),
('AMH', 'American Homes 4 Rent Common Shares of Beneficial Interest'),
('AMLX', 'Amylyx Pharmaceuticals'),
('AMN', 'AMN Healthcare Services Inc'),
('AMP', 'Ameriprise Financial'),
('AMPH', 'Amphastar Pharmaceuticals'),
('AMPL', 'Amplitude'),
('AMPX', 'Amprius Technologies'),
('AMRC', 'Ameresco'),
('AMRK', 'A-Mark Precious Metals'),
('AMRX', 'Amneal Pharmaceuticals'),
('AMRZ', 'Amrize Ltd'),
('AMSC', 'American Superconductor'),
('AMT', 'American Tower Corporation'),
('AMTB', 'Amerant Bancorp'),
('AMTM', 'Amentum Holdings'),
('AMZN', 'Amazon.com'),
('AMZU', 'Direxion Daily AMZN Bull 2X Shares'),
('AN', 'AutoNation'),
('ANAB', 'AnaptysBio'),
('ANET', 'Arista Networks'),
('ANF', 'Abercrombie & Fitch Company'),
('ANGI', 'Angi'),
('ANGO', 'AngioDynamics'),
('ANGX', 'Angel Studios'),
('ANIP', 'ANI Pharmaceuticals'),
('ANRO', 'Alto Neuroscience'),
('AOD', 'abrdn Total Dynamic Dividend Fund Common Shares of Beneficial Interest'),
('AON', 'Aon'),
('AORT', 'Artivion'),
('AOS', 'A.O. Smith'),
('APA', 'APA'),
('APAM', 'Artisan Partners Asset Management'),
('APD', 'Air Products and Chemicals'),
('APEI', 'American Public Education'),
('APG', 'APi Group'),
('APGE', 'Apogee Therapeutics'),
('APH', 'Amphenol'),
('APLD', 'Applied Digital'),
('APLE', 'Apple Hospitality REIT Inc. Common Shares'),
('APLS', 'Apellis Pharmaceuticals'),
('APO', 'Apollo Global Management Inc.'),
('APP', 'Applovin'),
('APPF', 'AppFolio'),
('APPN', 'Appian'),
('APPS', 'Digital Turbine'),
('APTV', 'Aptiv PLC'),
('AQMS', 'Aqua Metals'),
('AQN', 'Algonquin Power & Utilities Corp. Common Shares'),
('AQST', 'Aquestive Therapeutics'),
('AR', 'Antero Resources'),
('ARCC', 'Ares Capital'),
('ARCO', 'Arcos Dorados Holdings'),
('ARCT', 'Arcturus Therapeutics Holdings'),
('ARDT', 'Ardent Health'),
('ARDX', 'Ardelyx'),
('ARE', 'Alexandria Real Estate Equities'),
('ARES', 'Ares Management'),
('ARGX', 'argenx SE'),
('ARHS', 'Arhaus'),
('ARI', 'Apollo Commercial Real Estate Finance Inc'),
('ARKB', 'ARK 21Shares Bitcoin ETF Beneficial Interest'),
('ARKX', 'ARK Space Exploration ETF'),
('ARLO', 'Arlo Technologies'),
('ARM', 'Arm Holdings plc'),
('ARMK', 'Aramark'),
('ARMN', 'Aris Mining Corporation Common Shares'),
('AROC', 'Archrock'),
('ARQQ', 'Arqit Quantum'),
('ARQT', 'Arcutis Biotherapeutics'),
('ARRY', 'Array Technologies'),
('ARTV', 'Artiva Biotherapeutics'),
('ARVN', 'Arvinas'),
('ARX', 'Accelerant Holdings'),
('AS', 'Amer Sports'),
('ASAN', 'Asana'),
('ASB', 'Associated Banc-Corp'),
('ASC', 'Ardmore Shipping'),
('ASGN', 'ASGN Incorporated'),
('ASH', 'Ashland'),
('ASML', 'ASML Holding N.V. New York Registry Shares'),
('ASO', 'Academy Sports and Outdoors'),
('ASPI', 'ASP Isotopes'),
('ASPN', 'Aspen Aerogels'),
('ASTS', 'AST SpaceMobile'),
('ASX', 'ASE Technology Holding Co. Ltd.'),
('ATAI', 'ATAI Life Sciences N.V. Common Shares'),
('ATAT', 'Atour Lifestyle Holdings Limited'),
('ATEC', 'Alphatec Holdings'),
('ATEN', 'A10 Networks'),
('ATHM', 'Autohome'),
('ATI', 'ATI'),
('ATLX', 'Atlas Lithium'),
('ATMU', 'Atmus Filtration Technologies'),
('ATO', 'Atmos Energy'),
('ATON', 'AlphaTON Capital'),
('ATRC', 'AtriCure'),
('ATRO', 'Astronics'),
('ATXS', 'Astria Therapeutics'),
('AUB', 'Atlantic Union Bankshares'),
('AUGO', 'Aura Minerals Inc. Common Shares'),
('AUPH', 'Aurinia Pharmaceuticals Inc'),
('AVA', 'Avista'),
('AVAH', 'Aveanna Healthcare Holdings'),
('AVAV', 'AeroVironment'),
('AVB', 'AvalonBay Communities'),
('AVBP', 'ArriVent BioPharma'),
('AVDL', 'Avadel Pharmaceuticals plc Ordinary Share'),
('AVGO', 'Broadcom'),
('AVNS', 'Avanos Medical'),
('AVNT', 'Avient'),
('AVPT', 'AvePoint'),
('AVT', 'Avnet'),
('AVTX', 'Avalo Therapeutics'),
('AVXL', 'Anavex Life Sciences'),
('AVY', 'Avery Dennison'),
('AWI', 'Armstrong World Industries Inc'),
('AWK', 'American Water Works Company'),
('AXGN', 'Axogen'),
('AXL', 'American Axle & Manufacturing Holdings'),
('AXON', 'Axon Enterprise'),
('AXP', 'American Express Company'),
('AXS', 'Axis Capital Holdings Limited'),
('AXSM', 'Axsome Therapeutics'),
('AXTA', 'Axalta Coating Systems Ltd. Common Shares'),
('AXTI', 'AXT Inc'),
('AZ', 'A2Z Cust2Mate Solutions Corp. Common Shares'),
('AZN', 'AstraZeneca PLC'),
('AZO', 'AutoZone'),
('B', 'Barrick Mining Corporation Common Shares'),
('BA', 'Boeing Company'),
('BABA', 'Alibaba Group Holding Limited'),
('BAC', 'Bank of America'),
('BAH', 'Booz Allen Hamilton Holding'),
('BALL', 'Ball'),
('BAM', 'Brookfield Asset Management Inc'),
('BANC', 'Banc of California'),
('BAX', 'Baxter International'),
('BBAI', 'BigBear.ai'),
('BBBY', 'Bed Bath & Beyond'),
('BBDC', 'Barings BDC'),
('BBIO', 'BridgeBio Pharma'),
('BBNX', 'Beta Bionics'),
('BBT', 'Beacon Financial'),
('BBVA', 'Banco Bilbao Vizcaya Argentaria S.A.'),
('BBWI', 'Bath & Body Works'),
('BBY', 'Best Buy Co.'),
('BC', 'Brunswick'),
('BCAT', 'BlackRock Capital Allocation Term Trust Common Shares of Beneficial Interest'),
('BCAX', 'Bicara Therapeutics'),
('BCC', 'Boise Cascade L.L.C.'),
('BCE', 'BCE'),
('BCRX', 'BioCryst Pharmaceuticals'),
('BCS', 'Barclays PLC'),
('BDJ', 'Blackrock Enhanced Equity Dividend Trust'),
('BDX', 'Becton Dickinson and Company'),
('BE', 'Bloom Energy'),
('BEAM', 'Beam Therapeutics'),
('BEN', 'Franklin Resources'),
('BEPC', 'Brookfield Renewable Corporation Brookfield Renewable'),
('BF-B', 'Brown–Forman'),
('BFAM', 'Bright Horizons Family Solutions'),
('BFH', 'Bread Financial Holdings'),
('BG', 'Bunge Limited Common Shares'),
('BGC', 'BGC Group'),
('BGY', 'Blackrock Enhanced International Dividend Trust'),
('BHC', 'Bausch Health Companies'),
('BHF', 'Brighthouse Financial'),
('BHK', 'Blackrock Core Bond Trust'),
('BHP', 'BHP Group Limited'),
('BHVN', 'Biohaven Ltd. Common Shares'),
('BIIB', 'Biogen'),
('BILI', 'Bilibili'),
('BILL', 'BILL Holdings'),
('BIOA', 'BioAge Labs'),
('BIPC', 'Brookfield Infrastructure Corporation Brookfield Infrastructure'),
('BIRK', 'Birkenstock Holding plc'),
('BITU', 'ProShares Ultra Bitcoin ETF'),
('BITX', '2x Bitcoin Strategy ETF'),
('BK', 'The Bank of New York Mellon'),
('BKD', 'Brookdale Senior Living'),
('BKE', 'Buckle Inc.'),
('BKH', 'Black Hills'),
('BKKT', 'Bakkt Holdings'),
('BKNG', 'Booking Holdings'),
('BKR', 'Baker Hughes'),
('BKSY', 'BlackSky Technology'),
('BKU', 'BankUnited Inc'),
('BL', 'BlackLine'),
('BLBD', 'Blue Bird'),
('BLCO', 'Bausch + Lomb Corporation Common Shares'),
('BLDR', 'Builders FirstSource'),
('BLK', 'BlackRock'),
('BLKB', 'Blackbaud'),
('BLSH', 'Bullish'),
('BLZE', 'Backblaze'),
('BMA', 'Banco Macro S.A. ADR (representing Ten'),
('BMBL', 'Bumble'),
('BMI', 'Badger Meter'),
('BMNR', 'BitMine Immersion Technologies Inc'),
('BMNU', 'T-REX 2X Long BMNR Daily Target ETF'),
('BMO', 'Bank Of Montreal'),
('BMRN', 'BioMarin Pharmaceutical'),
('BMY', 'Bristol-Myers Squibb Company'),
('BN', 'Brookfield'),
('BNC', 'CEA Industries'),
('BNL', 'Broadstone Net Lease'),
('BNS', 'Bank Nova Scotia Halifax Pfd 3'),
('BNTX', 'BioNTech SE'),
('BOH', 'Bank of Hawaii'),
('BOIL', 'ProShares Ultra Bloomberg Natural Gas 2x Shares'),
('BOOT', 'Boot Barn Holdings'),
('BOX', 'Box'),
('BP', 'BP p.l.c.'),
('BPOP', 'Popular'),
('BR', 'Broadridge Financial Solutions'),
('BRBR', 'BellRing Brands'),
('BRCB', 'Black Rock Coffee Bar Inc'),
('BRK-B', 'Berkshire Hathaway'),
('BRO', 'Brown & Brown'),
('BROS', 'Dutch Bros'),
('BRSL', 'Brightstar Lottery PLC Trading under the Legal Name to begin at the market open on July 21 2025.'),
('BRSP', 'BrightSpire Capital'),
('BRX', 'Brixmor Property Group'),
('BRZE', 'Braze'),
('BSX', 'Boston Scientific'),
('BSY', 'Bentley Systems Incorporated'),
('BTC', 'Grayscale Bitcoin Mini Trust ETF'),
('BTI', 'British American Tobacco Industries p.l.c.'),
('BTM', 'Bitcoin Depot'),
('BTQ', 'BTQ Technologies'),
('BTSG', 'BrightSpring Health Services'),
('BTX', 'BlackRock Technology and Private Equity Term Trust Common Shares of Beneficial Interest'),
('BUD', 'Anheuser-Busch Inbev SA Sponsored ADR'),
('BURL', 'Burlington Stores'),
('BUSE', 'First Busey'),
('BV', 'BrightView Holdings'),
('BVFL', 'BV Financial'),
('BVN', 'Buenaventura Mining Company'),
('BWA', 'BorgWarner'),
('BWIN', 'The Baldwin Insurance Group'),
('BWLP', 'BW LPG Limited Common Shares'),
('BWXT', 'BWX Technologies'),
('BX', 'Blackstone'),
('BXMT', 'Blackstone Mortgage Trust'),
('BXP', 'BXP'),
('BXSL', 'Blackstone Secured Lending Fund Common Shares of Beneficial Interest'),
('BYD', 'Boyd Gaming'),
('BYRN', 'Byrna Technologies'),
('BZ', 'KANZHUN LIMITED American Depository Shares'),
('C', 'Citigroup'),
('CAAP', 'Corporacion America Airports SA Common Shares'),
('CADE', 'Cadence Bank'),
('CADL', 'Candel Therapeutics'),
('CAE', 'CAE'),
('CAG', 'ConAgra Brands'),
('CAH', 'Cardinal Health'),
('CAI', 'Caris Life Sciences'),
('CAKE', 'Cheesecake Factory Incorporated'),
('CAL', 'Caleres'),
('CALM', 'Cal-Maine Foods'),
('CALX', 'Calix Inc'),
('CAMT', 'Camtek Ltd.'),
('CARG', 'CarGurus'),
('CARR', 'Carrier Global'),
('CARS', 'Cars.com'),
('CART', 'Maplebear'),
('CAT', 'Caterpillar'),
('CAVA', 'CAVA Group'),
('CB', 'Chubb Limited'),
('CBOE', 'Cboe Global Markets'),
('CBRE', 'CBRE Group Inc'),
('CBRL', 'Cracker Barrel Old Country Store Inc'),
('CBSH', 'Commerce Bancshares'),
('CBZ', 'CBIZ'),
('CC', 'Chemours Company'),
('CCCS', 'CCC Intelligent Solutions Holdings'),
('CCEP', 'Coca-Cola Europacific Partners plc'),
('CCI', 'Crown Castle'),
('CCJ', 'Cameco'),
('CCK', 'Crown Holdings'),
('CCL', 'Carnival'),
('CCOI', 'Cogent Communications Holdings'),
('CCS', 'Century Communities'),
('CCUP', 'T-REX 2X Long CRCL Daily Target ETF'),
('CDE', 'Coeur Mining'),
('CDNA', 'CareDx'),
('CDNS', 'Cadence Design Systems'),
('CDP', 'COPT Defense Properties Common Shares of Beneficial Interest'),
('CDTX', 'Cidara Therapeutics'),
('CDW', 'CDW'),
('CDZI', 'CADIZ'),
('CE', 'Celanese'),
('CECO', 'CECO Environmental'),
('CEG', 'Constellation Energy'),
('CELC', 'Celcuity'),
('CELH', 'Celsius Holdings'),
('CENTA', 'Central Garden & Pet Company'),
('CENX', 'Century Aluminum Company'),
('CERT', 'Certara'),
('CF', 'CF Industries Holdings'),
('CFFN', 'Capitol Federal Financial'),
('CFG', 'Citizens Financial Group'),
('CFLT', 'Confluent'),
('CG', 'The Carlyle Group'),
('CGBD', 'Carlyle Secured Lending'),
('CGEM', 'Cullinan Therapeutics'),
('CGNX', 'Cognex'),
('CGON', 'CG Oncology'),
('CHA', 'Chagee Holdings Limited'),
('CHD', 'Church & Dwight Company'),
('CHDN', 'Churchill Downs Incorporated'),
('CHH', 'Choice Hotels International'),
('CHKP', 'Check Point Software Technologies Ltd.'),
('CHRD', 'Chord Energy'),
('CHRW', 'C.H. Robinson'),
('CHTR', 'Charter Communications'),
('CHWY', 'Chewy'),
('CHYM', 'Chime Financial'),
('CI', 'The Cigna Group'),
('CIEN', 'Ciena'),
('CIM', 'Chimera Investment'),
('CINF', 'Cincinnati Financial'),
('CIO', 'City Office REIT'),
('CIVI', 'Civitas Resources'),
('CL', 'Colgate-Palmolive Company'),
('CLB', 'Core Laboratories'),
('CLBT', 'Cellebrite DI Ltd.'),
('CLDT', 'Chatham Lodging Trust (REIT) Common Shares of Beneficial Interest'),
('CLDX', 'Celldex Therapeutics'),
('CLF', 'Cleveland-Cliffs'),
('CLH', 'Clean Harbors'),
('CLM', 'Cornerstone Strategic Investment Fund Inc. Common Shares'),
('CLMT', 'Calumet'),
('CLPT', 'ClearPoint Neuro'),
('CLS', 'Celestica'),
('CLSK', 'CleanSpark'),
('CLX', 'Clorox Company'),
('CM', 'Canadian Imperial Bank of Commerce'),
('CMA', 'Comerica Incorporated'),
('CMBT', 'CMB.TECH NV'),
('CMC', 'Commercial Metals Company'),
('CMCL', 'Caledonia Mining Corporation Plc Common Shares'),
('CMCSA', 'Comcast'),
('CME', 'CME Group'),
('CMG', 'Chipotle Mexican Grill'),
('CMI', 'Cummins'),
('CMP', 'Compass Minerals Intl Inc'),
('CMPO', 'CompoSecure'),
('CMPS', 'COMPASS Pathways Plc American Depository Shares'),
('CMRE', 'Costamare'),
('CMS', 'CMS Energy'),
('CNA', 'CNA Financial'),
('CNC', 'Centene'),
('CNH', 'CNH Industrial N.V. Common Shares'),
('CNI', 'Canadian National Railway Company'),
('CNK', 'Cinemark Holdings Inc Cinemark Holdings'),
('CNM', 'Core & Main'),
('CNO', 'CNO Financial Group'),
('CNP', 'CenterPoint Energy Inc'),
('CNQ', 'Canadian Natural Resources Limited'),
('CNS', 'Cohen & Steers Inc'),
('CNTA', 'Centessa Pharmaceuticals plc'),
('CNX', 'CNX Resources'),
('CNXC', 'Concentrix'),
('COCO', 'The Vita Coco Company'),
('CODI', 'D/B/A Compass Diversified Holdings Shares of Beneficial Interest'),
('COF', 'Capital One Financial'),
('COGT', 'Cogent Biosciences'),
('COIN', 'Coinbase Global'),
('COKE', 'Coca-Cola Consolidated'),
('COLB', 'Columbia Banking System'),
('COLD', 'Americold Realty Trust'),
('COLM', 'Columbia Sportswear Company'),
('COMM', 'CommScope Holding Company'),
('COMP', 'Compass'),
('CON', 'Concentra Group Holdings Parent'),
('CONI', 'GraniteShares 2x Short COIN Daily ETF'),
('COO', 'The Cooper Companies'),
('COP', 'ConocoPhillips'),
('COR', 'Cencora'),
('CORT', 'Corcept Therapeutics Incorporated'),
('CORZ', 'Core Scientific'),
('COST', 'Costco Wholesale'),
('CP', 'Canadian Pacific Kansas City Limited Common Shares'),
('CPAY', 'Corpay'),
('CPB', 'Campbell Soup Company'),
('CPNG', 'Coupang'),
('CPRI', 'Capri Holdings Limited'),
('CPRT', 'Copart Inc.'),
('CPRX', 'Catalyst Pharmaceuticals'),
('CPS', 'Cooper-Standard Holdings'),
('CPT', 'Camden Property Trust'),
('CRBG', 'Corebridge Financial'),
('CRBP', 'Corbus Pharmaceuticals Holdings'),
('CRC', 'California Resources'),
('CRCA', 'ProShares Ultra CRCL'),
('CRCG', 'Leverage Shares 2X Long CRCL Daily ETF'),
('CRCL', 'Circle Internet Group'),
('CRCT', 'Cricut'),
('CRDO', 'Credo Technology Group Holding Ltd'),
('CRESY', 'Cresud S.A.C.I.F. y A.'),
('CRF', 'Cornerstone Total Return Fund Inc.'),
('CRGY', 'Crescent Energy Company'),
('CRH', 'CRH PLC'),
('CRK', 'Comstock Resources'),
('CRL', 'Charles River Laboratories International'),
('CRM', 'Salesforce'),
('CRMD', 'CorMedix'),
('CRML', 'Critical Metals'),
('CRNC', 'Cerence'),
('CRNX', 'Crinetics Pharmaceuticals'),
('CROX', 'Crocs'),
('CRS', 'Carpenter Technology'),
('CRSP', 'CRISPR Therapeutics AG Common Shares'),
('CRTO', 'Criteo S.A.'),
('CRUS', 'Cirrus Logic'),
('CRVS', 'Corvus Pharmaceuticals'),
('CRWD', 'CrowdStrike Holdings'),
('CRWV', 'CoreWeave'),
('CSCO', 'Cisco Systems'),
('CSGP', 'CoStar Group'),
('CSIQ', 'Canadian Solar Inc. Common Shares'),
('CSL', 'Carlisle Companies Incorporated'),
('CSTM', 'Constellium SE'),
('CSWC', 'Capital Southwest'),
('CSX', 'CSX'),
('CTAS', 'Cintas'),
('CTLP', 'Cantaloupe'),
('CTO', 'CTO Realty Growth'),
('CTOS', 'Custom Truck One Source'),
('CTRA', 'Coterra Energy'),
('CTRE', 'CareTrust REIT'),
('CTRI', 'Centuri Holdings'),
('CTS', 'CTS'),
('CTSH', 'Cognizant Technology Solutions'),
('CTVA', 'Corteva'),
('CUBE', 'CubeSmart Common Shares'),
('CUBI', 'Customers Bancorp Inc'),
('CUK', 'Carnival Plc ADS ADS'),
('CURB', 'Curbline Properties'),
('CURI', 'CuriosityStream'),
('CUZ', 'Cousins Properties Incorporated'),
('CVAC', 'CureVac N.V.'),
('CVBF', 'CVB Financial'),
('CVE', 'Cenovus Energy Inc'),
('CVI', 'CVR Energy'),
('CVLT', 'Commvault Systems'),
('CVNA', 'Carvana Co.'),
('CVS', 'CVS Health'),
('CVX', 'Chevron'),
('CWAN', 'Clearwater Analytics Holdings'),
('CWEN', 'Clearway Energy'),
('CWH', 'Camping World Holdings'),
('CWK', 'Cushman & Wakefield plc'),
('CWST', 'Casella Waste Systems'),
('CWT', 'California Water Service Group'),
('CX', 'Cemex S.A.B. de C.V. Sponsored ADR'),
('CXM', 'Sprinklr'),
('CXT', 'Crane NXT Co.'),
('CYBN', 'Cybin Inc. Common Shares'),
('CYRX', 'CryoPort'),
('CYTK', 'Cytokinetics Incorporated'),
('CZR', 'Caesars Entertainment'),
('D', 'Dominion Energy'),
('DAKT', 'Daktronics'),
('DAL', 'Delta Air Lines'),
('DAN', 'Dana Incorporated'),
('DAR', 'Darling Ingredients'),
('DASH', 'DoorDash'),
('DAVE', 'Dave'),
('DAWN', 'Day One Biopharmaceuticals'),
('DAY', 'Dayforce'),
('DB', 'Deutsche Bank AG'),
('DBRG', 'DigitalBridge Group'),
('DBX', 'Dropbox'),
('DCI', 'Donaldson Company'),
('DCO', 'Ducommun Incorporated'),
('DCTH', 'Delcath Systems'),
('DD', 'DuPont de Nemours'),
('DDOG', 'Datadog'),
('DE', 'Deere & Company'),
('DEA', 'Easterly Government Properties'),
('DEC', 'Diversified Energy Company plc'),
('DECK', 'Deckers Outdoor'),
('DEI', 'Douglas Emmett'),
('DELL', 'Dell Technologies'),
('DEO', 'Diageo plc'),
('DFDV', 'DeFi Development'),
('DFIN', 'Donnelley Financial Solutions'),
('DG', 'Dollar General'),
('DGNX', 'Diginex Limited'),
('DGX', 'Quest Diagnostics Incorporated'),
('DGXX', 'Digi Power X Inc. Subordinate Voting Shares'),
('DHI', 'D.R. Horton'),
('DHR', 'Danaher Corporation'),
('DHT', 'DHT Holdings'),
('DIN', 'Dine Brands Global'),
('DINO', 'HF Sinclair'),
('DIS', 'Walt Disney Company'),
('DJCO', 'Daily Journal Corp.'),
('DJT', 'Trump Media & Technology Group'),
('DK', 'Delek US Holdings'),
('DKNG', 'DraftKings'),
('DLB', 'Dolby Laboratories'),
('DLO', 'DLocal Limited'),
('DLR', 'Digital Realty'),
('DLTR', 'Dollar Tree'),
('DNA', 'Ginkgo Bioworks Holdings'),
('DNLI', 'Denali Therapeutics'),
('DNP', 'DNP Select Income Fund'),
('DNTH', 'Dianthus Therapeutics'),
('DOC', 'Healthpeak Properties'),
('DOCN', 'DigitalOcean Holdings'),
('DOCS', 'Doximity'),
('DOLE', 'Dole plc'),
('DOMO', 'Domo'),
('DORM', 'Dorman Products'),
('DOV', 'Dover'),
('DOW', 'Dow Inc.'),
('DOX', 'Amdocs Limited'),
('DPRO', 'Draganfly Inc. Common Shares'),
('DQ', 'DAQO New Energy'),
('DRD', 'DRDGOLD Limited'),
('DRH', 'Diamondrock Hospitality Company'),
('DRI', 'Darden Restaurants'),
('DRS', 'Leonardo DRS'),
('DRVN', 'Driven Brands Holdings'),
('DSGN', 'Design Therapeutics'),
('DSGX', 'Descartes Systems Group Inc.'),
('DSL', 'DoubleLine Income Solutions Fund Common Shares of Beneficial Interests'),
('DT', 'Dynatrace'),
('DTE', 'DTE Energy Company'),
('DTM', 'DT Midstream'),
('DUK', 'Duke Energy Corporation'),
('DUOL', 'Duolingo'),
('DUOT', 'Duos Technologies Group'),
('DV', 'DoubleVerify Holdings'),
('DVA', 'DaVita'),
('DVAX', 'Dynavax Technologies'),
('DVN', 'Devon Energy'),
('DX', 'Dynex Capital'),
('DXC', 'DXC Technology Company'),
('DXCM', 'DexCom'),
('DXYZ', 'Destiny Tech100 Inc'),
('DY', 'Dycom Industries'),
('DYN', 'Dyne Therapeutics'),
('EA', 'Electronic Arts'),
('EAF', 'GrafTech International Ltd.'),
('EAT', 'Brinker International'),
('EBAY', 'eBay'),
('EBC', 'Eastern Bankshares'),
('EBS', 'Emergent BioSolutions'),
('EC', 'Ecopetrol S.A.'),
('ECC', 'Eagle Point Credit Company'),
('ECG', 'Everus Construction Group'),
('ECL', 'Ecolab'),
('ECVT', 'Ecovyst'),
('ED', 'Consolidated Edison'),
('EDN', 'Empresa Distribuidora Y Comercializadora Norte S.A.'),
('EE', 'Excelerate Energy'),
('EEFT', 'Euronet Worldwide'),
('EFC', 'Ellington Financial'),
('EFX', 'Equifax'),
('EFXT', 'Enerflex Ltd Common Shares'),
('EG', 'Everest Group'),
('EGBN', 'Eagle Bancorp'),
('EGO', 'Eldorado Gold'),
('EGP', 'EastGroup Properties'),
('EH', 'EHang Holdings Limited ADS'),
('EHAB', 'Enhabit'),
('EHC', 'Encompass Health'),
('EHTH', 'eHealth'),
('EIX', 'Edison International'),
('EL', 'Estee Lauder Companies Inc.'),
('ELAN', 'Elanco Animal Health Incorporated'),
('ELF', 'e.l.f. Beauty'),
('ELME', 'Elme Communities'),
('ELS', 'Equity Lifestyle Properties'),
('ELV', 'Elevance Health'),
('ELVN', 'Enliven Therapeutics'),
('EME', 'EMCOR Group'),
('EMN', 'Eastman Chemical Company'),
('EMPD', 'Empery Digital'),
('EMR', 'Emerson Electric'),
('ENB', 'Enbridge Inc'),
('ENOV', 'Enovis'),
('ENPH', 'Enphase Energy'),
('ENS', 'EnerSys'),
('ENSG', 'The Ensign Group'),
('ENTA', 'Enanta Pharmaceuticals'),
('ENTG', 'Entegris'),
('ENVA', 'Enova International'),
('ENVX', 'Enovix'),
('EOG', 'EOG Resources'),
('EOLS', 'Evolus'),
('EOSE', 'Eos Energy Enterprises'),
('EPAC', 'Enerpac Tool Group'),
('EPAM', 'EPAM Systems'),
('EPC', 'Edgewell Personal Care Company'),
('EPD', 'Enterprise Products Partners L.P.'),
('EPRT', 'Essential Properties Realty Trust'),
('EPSM', 'Epsium Enterprise Ltd'),
('EQH', 'Equitable Holdings'),
('EQIX', 'Equinix'),
('EQR', 'Equity Residential'),
('EQT', 'EQT'),
('EQX', 'Equinox Gold Corp. Common Shares'),
('ERIC', 'Ericsson'),
('ERIE', 'Erie Indemnity'),
('ERJ', 'Embraer S.A.'),
('ERO', 'Ero Copper Corp. Common Shares'),
('ES', 'Eversource Energy'),
('ESAB', 'ESAB'),
('ESI', 'Element Solutions'),
('ESNT', 'Essent Group Ltd. Common Shares'),
('ESRT', 'Empire State Realty Trust'),
('ESS', 'Essex Property Trust'),
('ESTA', 'Establishment Labs Holdings Inc. Common Shares'),
('ESTC', 'Elastic N.V.'),
('ETH', 'Grayscale Ethereum Mini Trust ETF'),
('ETHA', 'iShares Ethereum Trust ETF'),
('ETHD', 'Etho Climate Leadership U.S. ETF'),
('ETHE', 'Grayscale Ethereum Trust ETF'),
('ETHW', 'Bitwise Ethereum ETF Beneficial Interest'),
('ETHZ', 'ETHZilla'),
('ETN', 'Eaton Corporation PLC'),
('ETNB', '89bio'),
('ETR', 'Entergy'),
('ETSY', 'Etsy'),
('EVAX', 'Evaxion A/S'),
('EVH', 'Evolent Health Inc'),
('EVLV', 'Evolv Technologies Holdings'),
('EVRG', 'Evergy'),
('EW', 'Edwards Lifesciences'),
('EWBC', 'East West Bancorp'),
('EWTX', 'Edgewise Therapeutics'),
('EXAS', 'Exact Sciences'),
('EXC', 'Exelon'),
('EXE', 'Expand Energy'),
('EXEL', 'Exelixis'),
('EXG', 'Eaton Vance Tax-Managed Global Diversified Equity Income Fund Common Shares of Beneficial Interest'),
('EXK', 'Endeavour Silver'),
('EXLS', 'ExlService Holdings'),
('EXPD', 'Expeditors International of Washington'),
('EXPE', 'Expedia Group'),
('EXPI', 'eXp World Holdings'),
('EXPO', 'Exponent'),
('EXR', 'Extra Space Storage'),
('EYE', 'National Vision Holdings'),
('EYPT', 'EyePoint Pharmaceuticals'),
('F', 'Ford Motor Company'),
('FA', 'First Advantage'),
('FAF', 'First American Corporation'),
('FANG', 'Diamondback Energy'),
('FAST', 'Fastenal Company'),
('FBIN', 'Fortune Brands Innovations'),
('FBL', 'GraniteShares 2x Long META Daily ETF'),
('FBP', 'First BanCorp. New'),
('FBRT', 'Franklin BSP Realty Trust'),
('FCEL', 'FuelCell Energy'),
('FCF', 'First Commonwealth Financial'),
('FCN', 'FTI Consulting'),
('FCPT', 'Four Corners Property Trust'),
('FCX', 'Freeport-McMoRan'),
('FDMT', '4D Molecular Therapeutics'),
('FDS', 'FactSet Research Systems'),
('FDX', 'FedEx'),
('FE', 'FirstEnergy'),
('FERG', 'Ferguson Enterprises'),
('FETH', 'Fidelity Ethereum Fund Beneficial Interest'),
('FFBC', 'First Financial Bancorp.'),
('FFIN', 'First Financial Bankshares'),
('FFIV', 'F5'),
('FFWM', 'First Foundation'),
('FHB', 'First Hawaiian'),
('FHI', 'Federated Hermes'),
('FHN', 'First Horizon'),
('FI', 'Fiserv'),
('FIBK', 'First Interstate BancSystem'),
('FICO', 'Fair Isaac'),
('FIG', 'Figma'),
('FIGR', 'Figure Technology Solutions Inc'),
('FIGS', 'FIGS'),
('FINV', 'FinVolution Group'),
('FIP', 'FTAI Infrastructure'),
('FIS', 'Fidelity National Information Services'),
('FITB', 'Fifth Third Bancorp'),
('FIVE', 'Five Below'),
('FIVN', 'Five9'),
('FIX', 'Comfort Systems USA'),
('FIZZ', 'National Beverage'),
('FLEX', 'Flex Ltd.'),
('FLG', 'Flagstar Bank N.A.'),
('FLNC', 'Fluence Energy'),
('FLNG', 'FLEX LNG Ltd.'),
('FLO', 'Flowers Foods'),
('FLOC', 'Flowco Holdings'),
('FLS', 'Flowserve'),
('FLUT', 'Flutter Entertainment plc'),
('FLUX', 'Flux Power Holdings'),
('FLY', 'Firefly Aerospace'),
('FMC', 'FMC'),
('FMFC', 'Kandal M Venture Ltd'),
('FN', 'Fabrinet'),
('FNB', 'F.N.B.'),
('FND', 'Floor & Decor Holdings'),
('FNF', 'Fidelity National Financial'),
('FNV', 'Franco-Nevada'),
('FOFO', 'Hang Feng Technology Innovation Co Ltd'),
('FOLD', 'Amicus Therapeutics'),
('FORD', 'Forward Industries'),
('FORM', 'FormFactor Inc. FormFactor'),
('FOX', 'Fox'),
('FOXA', 'Fox'),
('FOXF', 'Fox Factory Holding'),
('FRGE', 'Forge Global Holdings'),
('FRMI', 'Fermi'),
('FRO', 'Frontline Plc'),
('FROG', 'JFrog Ltd.'),
('FRPT', 'Freshpet'),
('FRSH', 'Freshworks'),
('FRT', 'Federal Realty Investment Trust'),
('FSCO', 'FS Credit Opportunities'),
('FSK', 'FS KKR Capital'),
('FSLR', 'First Solar'),
('FSLY', 'Fastly'),
('FSM', 'Fortuna Mining Corp. Common Shares'),
('FSTR', 'L.B. Foster'),
('FSV', 'FirstService Corporation Common Shares'),
('FTAI', 'FTAI Aviation Ltd.'),
('FTEK', 'Fuel Tech'),
('FTI', 'TechnipFMC plc Ordinary Share'),
('FTK', 'Flotek Industries'),
('FTNT', 'Fortinet'),
('FTRE', 'Fortrea Holdings'),
('FTS', 'Fortis Inc. Common Shares'),
('FTV', 'Fortive'),
('FUL', 'H. B. Fuller Company'),
('FULT', 'Fulton Financial'),
('FUN', 'Six Flags Entertainment'),
('FWRD', 'Forward Air'),
('FWRG', 'First Watch Restaurant Group'),
('G', 'Genpact Limited'),
('GAB', 'Gabelli Equity Trust Inc.'),
('GAMB', 'Gambling.com Group Limited'),
('GAP', 'Gap Inc.'),
('GBCI', 'Glacier Bancorp'),
('GBDC', 'Golub Capital BDC'),
('GBTG', 'Global Business Travel Group'),
('GCMG', 'GCM Grosvenor'),
('GCT', 'GigaCloud Technology Inc'),
('GD', 'General Dynamics'),
('GDDY', 'GoDaddy'),
('GDOT', 'Green Dot'),
('GDS', 'GDS Holdings Limited ADS'),
('GDYN', 'Grid Dynamics Holdings'),
('GE', 'GE Aerospace'),
('GEHC', 'GE HealthCare Technologies'),
('GEMI', 'Gemini Space Station'),
('GEN', 'Gen Digital'),
('GENI', 'Genius Sports Limited'),
('GEO', 'Geo Group Inc (The) REIT'),
('GEOS', 'Geospace Technologies'),
('GES', 'Guess?'),
('GEV', 'GE Vernova'),
('GFI', 'Gold Fields Limited'),
('GFL', 'GFL Environmental Inc. Subordinate voting shares no par value'),
('GFS', 'GlobalFoundries'),
('GGAL', 'Grupo Financiero Galicia S.A.'),
('GGG', 'Graco'),
('GH', 'Guardant Health'),
('GIB', 'CGI'),
('GIL', 'Gildan Activewear'),
('GILD', 'Gilead Sciences'),
('GILT', 'Gilat Satellite Networks Ltd.'),
('GIS', 'General Mills'),
('GKOS', 'Glaukos'),
('GL', 'Globe Life'),
('GLAD', 'Gladstone Capital'),
('GLBE', 'Global-E Online Ltd.'),
('GLDD', 'Great Lakes Dredge & Dock'),
('GLNG', 'Golar Lng Ltd'),
('GLOB', 'Globant S.A. Common Shares'),
('GLPI', 'Gaming and Leisure Properties'),
('GLUE', 'Monte Rosa Therapeutics'),
('GLW', 'Corning Inc.'),
('GLXY', 'Galaxy Digital'),
('GM', 'General Motors Company'),
('GMAB', 'Genmab A/S ADS'),
('GME', 'GameStop'),
('GMED', 'Globus Medical'),
('GNK', 'Genco Shipping & Trading Limited'),
('GNL', 'Global Net Lease'),
('GNLX', 'Genelux'),
('GNRC', 'Generac Holdlings'),
('GNTX', 'Gentex'),
('GO', 'Grocery Outlet Holding'),
('GOF', 'Guggenheim Strategic Opportunities Fund Common Shares of Beneficial Interest'),
('GOGO', 'Gogo'),
('GOOD', 'Gladstone Commercial Corporation Real Estate Investment Trust'),
('GOOG', 'Alphabet'),
('GOOGL', 'Alphabet'),
('GOOS', 'Canada Goose Holdings Inc. Subordinate Voting Shares'),
('GPC', 'Genuine Parts Company'),
('GPK', 'Graphic Packaging Holding Company'),
('GPN', 'Global Payments'),
('GPRE', 'Green Plains'),
('GPRK', 'Geopark Ltd Common Shares'),
('GRAL', 'GRAIL'),
('GRDN', 'Guardian Pharmacy Services'),
('GRFS', 'Grifols S.A.'),
('GRMN', 'Garmin Ltd.'),
('GRND', 'Grindr'),
('GRNT', 'Granite Ridge Resources'),
('GRPN', 'Groupon'),
('GS', 'Goldman Sachs Group Inc.'),
('GSAT', 'Globalstar'),
('GSBD', 'Goldman Sachs BDC'),
('GSHD', 'Goosehead Insurance'),
('GSIT', 'GSI Technology'),
('GSK', 'GSK plc'),
('GSL', 'Global Ship Lease Inc New'),
('GSM', 'Ferroglobe PLC'),
('GT', 'The Goodyear Tire & Rubber Company'),
('GTES', 'Gates Industrial Corporation plc'),
('GTLB', 'GitLab'),
('GTLS', 'Chart Industries'),
('GTM', 'ZoomInfo Technologies Inc'),
('GTX', 'Garrett Motion'),
('GTY', 'Getty Realty'),
('GUSH', 'Direxion Daily S&P Oil & Gas Exp. & Prod. Bull 2X Shares'),
('GVA', 'Granite Construction Incorporated'),
('GWAV', 'Greenwave Technology Solutions Inc'),
('GWRE', 'Guidewire Software'),
('GWW', 'W. W. Grainger'),
('GXO', 'GXO Logistics'),
('H', 'Hyatt Hotels'),
('HAE', 'Haemonetics'),
('HAFN', 'Hafnia Limited Common Shares'),
('HAL', 'Halliburton Company'),
('HALO', 'Halozyme Therapeutics'),
('HAS', 'Hasbro'),
('HASI', 'HA Sustainable Infrastructure Capital'),
('HBAN', 'Huntington Bancshares Incorporated'),
('HBI', 'Hanesbrands'),
('HBM', 'Hudbay Minerals'),
('HBNC', 'Horizon Bancorp'),
('HCA', 'HCA Healthcare'),
('HCC', 'Warrior Met Coal'),
('HCSG', 'Healthcare Services Group'),
('HD', 'Home Depot Inc.'),
('HDB', 'HDFC Bank Limited'),
('HDSN', 'Hudson Technologies'),
('HE', 'Hawaiian Electric Industries'),
('HELE', 'Helen of Troy Limited'),
('HESM', 'Hess Midstream LP'),
('HGV', 'Hilton Grand Vacations'),
('HI', 'Hillenbrand Inc'),
('HIG', 'The Hartford Insurance Group'),
('HII', 'Huntington Ingalls Industries'),
('HIMS', 'Hims & Hers Health'),
('HIMX', 'Himax Technologies'),
('HIMZ', 'Defiance Daily Target 2X Long HIMS ETF'),
('HIVE', 'HIVE Digital Technologies Ltd. Common Shares'),
('HL', 'Hecla Mining Company'),
('HLF', 'Herbalife Ltd. Common Shares'),
('HLI', 'Houlihan Lokey'),
('HLIO', 'Helios Technologies'),
('HLIT', 'Harmonic'),
('HLMN', 'Hillman Solutions'),
('HLN', 'Haleon plc'),
('HLT', 'Hilton Worldwide Holdings'),
('HLX', 'Helix Energy Solutions Group'),
('HMC', 'Honda Motor Company Ltd.'),
('HMY', 'Harmony Gold Mining Company Limited'),
('HNGE', 'Hinge Health'),
('HNI', 'HNI'),
('HOG', 'Harley-Davidson'),
('HOLX', 'Hologic'),
('HOMB', 'Home BancShares'),
('HON', 'Honeywell International'),
('HONE', 'HarborOne Bancorp'),
('HOOD', 'Robinhood Markets'),
('HOPE', 'Hope Bancorp'),
('HOUS', 'Anywhere Real Estate'),
('HP', 'Helmerich & Payne'),
('HPE', 'Hewlett Packard Enterprise Company'),
('HPK', 'HighPeak Energy'),
('HPQ', 'HP'),
('HQL', 'abrdn Life Sciences Investors Shares of Beneficial Interest'),
('HQY', 'HealthEquity'),
('HRB', 'H&R Block'),
('HRI', 'Herc Holdings'),
('HRL', 'Hormel Foods'),
('HRMY', 'Harmony Biosciences Holdings'),
('HROW', 'Harrow Inc'),
('HRZN', 'Horizon Technology Finance'),
('HSAI', 'Hesai Group'),
('HSBC', 'HSBC Holdings plc.'),
('HSDT', 'Solana Company'),
('HSIC', 'Henry Schein'),
('HST', 'Host Hotels & Resorts'),
('HSY', 'The Hershey Company'),
('HTBK', 'Heritage Commerce Corp'),
('HTFL', 'Heartflow'),
('HTGC', 'Hercules Capital'),
('HTH', 'Hilltop Holdings'),
('HTHT', 'H World Group Limited'),
('HTLD', 'Heartland Express'),
('HTO', 'H2O America'),
('HTZ', 'Hertz Global Holdings Inc'),
('HUBB', 'Hubbell Inc'),
('HUBG', 'Hub Group'),
('HUBS', 'HubSpot'),
('HUM', 'Humana'),
('HUN', 'Huntsman'),
('HUSA', 'Houston American Energy'),
('HUT', 'Hut 8'),
('HWC', 'Hancock Whitney'),
('HWM', 'Howmet Aerospace'),
('HXL', 'Hexcel'),
('HYMC', 'Hycroft Mining Holding'),
('HYPD', 'Hyperion DeFi'),
('HYT', 'Blackrock Corporate High Yield Fund'),
('IAC', 'IAC'),
('IAG', 'Iamgold'),
('IART', 'Integra LifeSciences Holdings'),
('IAS', 'Integral Ad Science Holding'),
('IBIT', 'iShares Bitcoin Trust ETF'),
('IBM', 'International Business Machines'),
('IBN', 'ICICI Bank Limited'),
('IBP', 'Installed Building Products'),
('ICE', 'Intercontinental Exchange'),
('ICL', 'ICL Group Ltd.'),
('IDA', 'IDACORP'),
('IDXX', 'IDEXX Laboratories'),
('IDYA', 'IDEAYA Biosciences'),
('IE', 'Ivanhoe Electric'),
('IEP', 'Icahn Enterprises L.P.'),
('IEX', 'IDEX'),
('IFF', 'International Flavors & Fragrances'),
('ILMN', 'Illumina'),
('IMA', 'ImageneBio'),
('IMAX', 'Imax'),
('IMNM', 'Immunome'),
('IMO', 'Imperial Oil Limited'),
('IMPP', 'Imperial Petroleum Inc. Common Shares'),
('IMRX', 'Immuneering'),
('IMTX', 'Immatics N.V.'),
('IMVT', 'Immunovant'),
('INBX', 'Inhibrx Biosciences'),
('INCY', 'Incyte'),
('INDI', 'indie Semiconductor'),
('INDV', 'Indivior PLC'),
('INFA', 'Informatica'),
('INFY', 'Infosys Limited'),
('ING', 'ING Group N.V.'),
('INMD', 'InMode Ltd.'),
('INN', 'Summit Hotel Properties'),
('INOD', 'Innodata'),
('INSM', 'Insmed Incorporated'),
('INSP', 'Inspire Medical Systems'),
('INTA', 'Intapp'),
('INTC', 'Intel'),
('INTU', 'Intuit'),
('INVA', 'Innoviva'),
('INVH', 'Invitation Homes'),
('INVX', 'Innovex International'),
('IONQ', 'IonQ'),
('IONS', 'Ionis Pharmaceuticals'),
('IOT', 'Samsara'),
('IP', 'International Paper Company'),
('IPG', 'Interpublic Group of Companies Inc.'),
('IQV', 'IQVIA Holdings'),
('IR', 'Ingersoll Rand'),
('IRDM', 'Iridium Communications Inc'),
('IREN', 'IREN Limited'),
('IRM', 'Iron Mountain Incorporated (Delaware)Common Stock REIT'),
('IRON', 'Disc Medicine'),
('IRS', 'IRSA Inversiones Y Representaciones S.A. Global'),
('IRT', 'Independence Realty Trust'),
('ISRG', 'Intuitive Surgical'),
('ISSC', 'Innovative Solutions and Support'),
('IT', 'Gartner'),
('ITRI', 'Itron'),
('ITT', 'ITT'),
('ITW', 'Illinois Tool Works'),
('IVT', 'InvenTrust Properties'),
('IVZ', 'Invesco Ltd'),
('J', 'Jacobs Solutions'),
('JACK', 'Jack In The Box'),
('JAMF', 'Jamf Holding'),
('JANX', 'Janux Therapeutics'),
('JAZZ', 'Jazz Pharmaceuticals plc'),
('JBGS', 'JBG SMITH Properties Common Shares'),
('JBHT', 'J.B. Hunt Transport Services'),
('JBI', 'Janus International Group'),
('JBL', 'Jabil'),
('JBS', 'JBS N.V.'),
('JBTM', 'JBT Marel'),
('JCI', 'Johnson Controls International plc Ordinary Share'),
('JD', 'JD.com'),
('JEF', 'Jefferies Financial Group'),
('JHG', 'Janus Henderson Group plc'),
('JHX', 'James Hardie Industries plc.'),
('JKHY', 'Jack Henry & Associates'),
('JKS', 'JinkoSolar Holding Company Limited'),
('JMIA', 'Jumia Technologies AG'),
('JNJ', 'Johnson & Johnson'),
('JOBY', 'Joby Aviation'),
('JPM', 'JP Morgan Chase & Co.'),
('JQC', 'Nuveen Credit Strategies Income Fund Shares of Beneficial Interest'),
('JXN', 'Jackson Financial'),
('K', 'Kellanova'),
('KALA', 'Kala Bio Inc'),
('KALV', 'KalVista Pharmaceuticals'),
('KBH', 'KB Home'),
('KBR', 'KBR Inc'),
('KC', 'Kingsoft Cloud Holdings Limited'),
('KD', 'Kyndryl Holdings'),
('KDK', 'Kodiak AI'),
('KDP', 'Keurig Dr Pepper'),
('KEP', 'Korea Electric Power'),
('KEX', 'Kirby'),
('KEY', 'KeyCorp'),
('KEYS', 'Keysight Technologies'),
('KGC', 'Kinross Gold'),
('KGS', 'Kodiak Gas Services'),
('KHC', 'The Kraft Heinz Company'),
('KIM', 'Kimco Realty Corporation'),
('KIO', 'KKR Income Opportunities Fund Common Shares'),
('KKR', 'KKR'),
('KLAC', 'KLA'),
('KLC', 'KinderCare Learning Companies'),
('KLIC', 'Kulicke and Soffa Industries'),
('KMB', 'Kimberly-Clark'),
('KMI', 'Kinder Morgan'),
('KMPR', 'Kemper Corporation'),
('KMT', 'Kennametal'),
('KMTS', 'Kestra Medical Technologies Ltd.'),
('KMX', 'CarMax Inc'),
('KN', 'Knowles'),
('KNF', 'Knife Riv Holding Co.'),
('KNSL', 'Kinsale Capital Group'),
('KNTK', 'Kinetik Holdings'),
('KNX', 'Knight-Swift Transportation Holdings'),
('KO', 'Coca-Cola Company'),
('KOD', 'Kodiak Sciences Inc'),
('KODK', 'Eastman Kodak Company Common New'),
('KOPN', 'Kopin Corporation'),
('KR', 'Kroger'),
('KRC', 'Kilroy Realty'),
('KREF', 'KKR Real Estate Finance Trust'),
('KRG', 'Kite Realty Group Trust'),
('KRMN', 'Karman Holdings'),
('KRNT', 'Kornit Digital Ltd.'),
('KRNY', 'Kearny Financial Corp'),
('KROS', 'Keros Therapeutics'),
('KRUS', 'Kura Sushi USA'),
('KSCP', 'Knightscope'),
('KSPI', 'Joint Stock Company Kaspi.kz American Depository Shares'),
('KT', 'KT'),
('KTB', 'Kontoor Brands'),
('KTOS', 'Kratos Defense & Security Solutions'),
('KURA', 'Kura Oncology'),
('KVUE', 'Kenvue'),
('KVYO', 'Klaviyo Inc'),
('KYIV', 'Kyivstar Group Ltd. Common Shares'),
('KYN', 'Kayne Anderson Energy Infrastructure Fund'),
('KYTX', 'Kyverna Therapeutics'),
('KZIA', 'Kazia Therapeutics Limited'),
('L', 'Loews'),
('LABD', 'Direxion Daily S&P Biotech Bear 3X Shares'),
('LAC', 'Lithium Americas Corp. Common Shares'),
('LAD', 'Lithia Motors'),
('LAES', 'SEALSQ Corp'),
('LAND', 'Gladstone Land'),
('LAZ', 'Lazard'),
('LB', 'LandBridge Company LLC'),
('LBRDK', 'Liberty Broadband'),
('LBRT', 'Liberty Energy'),
('LBTYA', 'Liberty Global Ltd.'),
('LBTYK', 'Liberty Global Ltd.'),
('LC', 'LendingClub'),
('LCID', 'Lucid Group'),
('LDOS', 'Leidos Holdings'),
('LEA', 'Lear'),
('LECO', 'Lincoln Electric Holdings Inc. Common Shares'),
('LEG', 'Leggett & Platt Incorporated'),
('LEGN', 'Legend Biotech'),
('LEN', 'Lennar'),
('LENZ', 'LENZ Therapeutics'),
('LEVI', 'Levi Strauss & Co'),
('LFMD', 'LifeMD'),
('LFST', 'LifeStance Health Group'),
('LGIH', 'LGI Homes'),
('LGN', 'Legence'),
('LH', 'Labcorp Holdings'),
('LHX', 'L3Harris Technologies'),
('LI', 'Li Auto'),
('LIF', 'Life360'),
('LII', 'Lennox International'),
('LILA', 'Liberty Latin America Ltd.'),
('LILAK', 'Liberty Latin America Ltd.'),
('LIN', 'Linde plc'),
('LIND', 'Lindblad Expeditions Holdings'),
('LINE', 'Lineage'),
('LION', 'Lionsgate Studios Corp Common Shares'),
('LITE', 'Lumentum Holdings'),
('LIVN', 'LivaNova PLC'),
('LKQ', 'LKQ'),
('LLY', 'Eli Lilly and Company'),
('LMND', 'Lemonade'),
('LMT', 'Lockheed Martin'),
('LNC', 'Lincoln National'),
('LNG', 'Cheniere Energy'),
('LNT', 'Alliant Energy'),
('LNTH', 'Lantheus Holdings'),
('LOCO', 'El Pollo Loco Holdings'),
('LOGI', 'Logitech International S.A.'),
('LOMA', 'Loma Negra Compania Industrial Argentina Sociedad Anonima ADS'),
('LOVE', 'The Lovesac Company'),
('LPG', 'Dorian LPG Ltd.'),
('LPLA', 'LPL Financial Holdings'),
('LPSN', 'LivePerson'),
('LPTH', 'LightPath Technologies'),
('LPX', 'Louisiana-Pacific'),
('LQDA', 'Liquidia'),
('LRCX', 'Lam Research'),
('LRN', 'Stride'),
('LSCC', 'Lattice Semiconductor'),
('LSPD', 'Lightspeed Commerce Inc. Subordinate Voting Shares'),
('LTBR', 'Lightbridge Corporation'),
('LTC', 'LTC Properties'),
('LTH', 'Life Time Group Holdings'),
('LTM', 'LATAM Airlines Group S.A.'),
('LULU', 'Lululemon Athletica'),
('LUMN', 'Lumen Technologies'),
('LUV', 'Southwest Airlines Company'),
('LVS', 'Las Vegas Sands'),
('LW', 'Lamb Weston'),
('LX', 'LexinFintech Holdings Ltd.'),
('LXEO', 'Lexeo Therapeutics'),
('LXP', 'LXP Industrial Trust'),
('LYB', 'LyondellBasell Industries NV'),
('LYFT', 'Lyft'),
('LYV', 'Live Nation Entertainment'),
('LZ', 'LegalZoom.com'),
('MA', 'Mastercard Incorporated'),
('MAA', 'Mid-America Apartment Communities'),
('MAC', 'Macerich Company'),
('MAGN', 'Magnera'),
('MAIN', 'Main Street Capital'),
('MAN', 'ManpowerGroup'),
('MANH', 'Manhattan Associates'),
('MAPS', 'WM Technology'),
('MAR', 'Marriott International'),
('MARA', 'MARA Holdings'),
('MAS', 'Masco'),
('MASI', 'Masimo'),
('MAT', 'Mattel'),
('MATX', 'Matson'),
('MAX', 'MediaAlpha'),
('MBC', 'MasterBrand'),
('MBLY', 'Mobileye Global'),
('MBX', 'MBX Biosciences'),
('MC', 'Moelis & Company'),
('MCHP', 'Microchip Technology Incorporated'),
('MCK', 'McKesson'),
('MD', 'Pediatrix Medical Group'),
('MDB', 'MongoDB'),
('MDLZ', 'Mondelez International'),
('MDT', 'Medtronic plc.'),
('MDXG', 'MiMedx Group Inc'),
('MEDP', 'Medpace Holdings'),
('MEG', 'Montrose Environmental Group'),
('MELI', 'MercadoLibre'),
('MENS', 'Jyong Biotech Ltd.'),
('MEOH', 'Methanex'),
('MET', 'MetLife'),
('META', 'Meta Platforms'),
('METC', 'Ramaco Resources'),
('METU', 'Direxion Daily META Bull 2X Shares'),
('MFA', 'MFA Financial'),
('MFC', 'Manulife Financial'),
('MFG', 'Mizuho Financial Group Inc. Sponosred ADR'),
('MFIC', 'MidCap Financial Investment'),
('MGA', 'Magna International'),
('MGM', 'MGM Resorts International'),
('MGNI', 'Magnite'),
('MGY', 'Magnolia Oil & Gas'),
('MHK', 'Mohawk Industries'),
('MIAX', 'Miami International Holdings'),
('MIDD', 'Middleby Corporation'),
('MIND', 'MIND Technology'),
('MIRM', 'Mirum Pharmaceuticals'),
('MKC', 'McCormick & Company Incorporated'),
('MKSI', 'MKS'),
('MKTX', 'MarketAxess Holdings'),
('MLCO', 'Melco Resorts & Entertainment Limited'),
('MLI', 'Mueller Industries'),
('MLKN', 'MillerKnoll'),
('MLM', 'Martin Marietta Materials'),
('MLYS', 'Mineralys Therapeutics'),
('MMC', 'Marsh & McLennan Companies'),
('MMM', '3M Company'),
('MMS', 'Maximus'),
('MMSI', 'Merit Medical Systems'),
('MMYT', 'MakeMyTrip Limited'),
('MNDY', 'monday.com Ltd.'),
('MNKD', 'MannKind'),
('MNMD', 'Mind Medicine (MindMed) Inc. Common Shares'),
('MNRO', 'Monro'),
('MNSO', 'MINISO Group Holding Limited'),
('MNST', 'Monster Beverage'),
('MNTN', 'MNTN'),
('MO', 'Altria Group'),
('MOD', 'Modine Manufacturing Company'),
('MODG', 'Topgolf Callaway Brands'),
('MOFG', 'MidWestOne Financial Gp'),
('MOH', 'Molina Healthcare Inc'),
('MOMO', 'Hello Group'),
('MORN', 'Morningstar'),
('MOS', 'Mosaic Company'),
('MP', 'MP Materials'),
('MPC', 'Marathon Petroleum'),
('MPLT', 'MapLight Therapeutics'),
('MPWR', 'Monolithic Power Systems'),
('MQ', 'Marqeta'),
('MQY', 'Blackrock MuniYield Quality Fund'),
('MRC', 'MRC Global'),
('MRCY', 'Mercury Systems Inc'),
('MRK', 'Merck & Company'),
('MRNA', 'Moderna'),
('MRP', 'Millrose Properties'),
('MRTN', 'Marten Transport Ltd.'),
('MRUS', 'Merus N.V. Common Shares'),
('MRVL', 'Marvell Technology'),
('MRX', 'Marex Group plc'),
('MS', 'Morgan Stanley'),
('MSCI', 'MSCI'),
('MSDL', 'Morgan Stanley Direct Lending Fund'),
('MSFT', 'Microsoft'),
('MSI', 'Motorola Solutions'),
('MSIF', 'MSC Income Fund'),
('MSM', 'MSC Industrial Direct Company'),
('MSOX', 'AdvisorShares MSOS 2x Daily ETF'),
('MSTX', 'Defiance Daily Target 2x Long MSTR ETF'),
('MT', 'Arcelor Mittal NY Registry Shares NEW'),
('MTA', 'Metalla Royalty & Streaming Ltd. Common Shares'),
('MTB', 'M&T Bank'),
('MTCH', 'Match Group'),
('MTD', 'Mettler Toledo'),
('MTDR', 'Matador Resources Co'),
('MTG', 'MGIC Investment'),
('MTH', 'Meritage Homes'),
('MTN', 'Vail Resorts'),
('MTSI', 'MACOM Technology Solutions Holdings'),
('MTZ', 'MasTec'),
('MU', 'Micron Technology'),
('MUFG', 'Mitsubishi UFJ Financial Group'),
('MUSA', 'Murphy USA'),
('MUX', 'McEwen'),
('MVST', 'Microvast Holdings'),
('MWA', 'MUELLER WATER PRODUCTS'),
('MXL', 'MaxLinear'),
('MYGN', 'Myriad Genetics'),
('MYI', 'Blackrock MuniYield Quality Fund III Inc'),
('NABL', 'N-able'),
('NAC', 'Nuveen California Quality Municipal Income Fund'),
('NAD', 'Nuveen Quality Municipal Income Fund'),
('NAGE', 'Niagen Bioscience'),
('NAMS', 'NewAmsterdam Pharma Company N.V.'),
('NATL', 'NCR Atleos Corp'),
('NAVI', 'Navient'),
('NB', 'NioCorp Developments Ltd.'),
('NBIX', 'Neurocrine Biosciences'),
('NCLH', 'Norwegian Cruise Line Holdings Ltd.'),
('NCNO', 'nCino'),
('NDAQ', 'Nasdaq'),
('NDSN', 'Nordson'),
('NE', 'Noble Corporation plc A'),
('NEA', 'Nuveen AMT-Free Quality Municipal Income Fund Common Shares of Beneficial Interest Par Value $.01'),
('NEE', 'NextEra Energy'),
('NEGG', 'Newegg Commerce Inc. Common Shares'),
('NEM', 'Newmont'),
('NEO', 'NeoGenomics'),
('NEOG', 'Neogen'),
('NET', 'Cloudflare'),
('NEXN', 'Nexxen International Ltd.'),
('NEXT', 'NextDecade'),
('NFBK', 'Northfield Bancorp'),
('NFG', 'National Fuel Gas Company'),
('NFLX', 'Netflix'),
('NG', 'Novagold Resources'),
('NGD', 'New Gold'),
('NGG', 'National Grid Transco PLC National Grid PLC'),
('NGNE', 'Neurogene'),
('NI', 'NiSource Inc'),
('NICE', 'NICE Ltd'),
('NIO', 'NIO'),
('NIQ', 'NIQ Global Intelligence plc'),
('NKE', 'Nike'),
('NLY', 'Annaly Capital Management'),
('NMAX', 'Newsmax'),
('NMFC', 'New Mountain Finance'),
('NMIH', 'NMI Holdings'),
('NMRK', 'Newmark Group'),
('NN', 'NextNav'),
('NNE', 'Nano Nuclear Energy'),
('NNN', 'NNN REIT'),
('NOC', 'Northrop Grumman'),
('NOG', 'Northern Oil and Gas'),
('NOK', 'Nokia Corporation Sponsored'),
('NOMD', 'Nomad Foods Limited'),
('NOV', 'NOV'),
('NOVT', 'Novanta'),
('NOW', 'ServiceNow'),
('NP', 'Neptune Insurance Holdings Inc'),
('NPKI', 'NPK International'),
('NPT', 'Texxon Holding Limited'),
('NRDS', 'NerdWallet'),
('NRG', 'NRG Energy'),
('NRIX', 'Nurix Therapeutics'),
('NRK', 'Nuveen New York AMT-Free Quality Municipal Income Fund'),
('NSA', 'National Storage Affiliates Trust Common Shares of Beneficial Interest'),
('NSC', 'Norfolk Southern'),
('NSIT', 'Insight Enterprises'),
('NSP', 'Insperity'),
('NTAP', 'NetApp'),
('NTCT', 'NetScout Systems'),
('NTES', 'NetEase'),
('NTLA', 'Intellia Therapeutics'),
('NTNX', 'Nutanix'),
('NTRA', 'Natera'),
('NTRS', 'Northern Trust'),
('NTSK', 'Netskope'),
('NTST', 'NetSTREIT'),
('NUAI', 'New Era Energy & Digital'),
('NUE', 'Nucor'),
('NUKK', 'Nukkleus'),
('NUS', 'Nu Skin Enterprises'),
('NUV', 'Nuveen Municipal Value Fund'),
('NUVB', 'Nuvation Bio'),
('NUVL', 'Nuvalent'),
('NVAX', 'Novavax'),
('NVDA', 'NVIDIA'),
('NVDD', 'Direxion Daily NVDA Bear 1X Shares'),
('NVFY', 'Nova Lifestyle'),
('NVG', 'Nuveen AMT-Free Municipal Credit Income Fund'),
('NVGS', 'Navigator Holdings Ltd.'),
('NVMI', 'Nova Ltd.'),
('NVO', 'Novo Nordisk A/S'),
('NVR', 'NVR, Inc.'),
('NVRI', 'Enviri'),
('NVS', 'Novartis AG'),
('NVST', 'Envista Holdings'),
('NVT', 'nVent Electric plc'),
('NVTS', 'Navitas Semiconductor'),
('NWBI', 'Northwest Bancshares'),
('NWG', 'NatWest Group plc'),
('NWL', 'Newell Brands'),
('NWS', 'News'),
('NWSA', 'News'),
('NX', 'Quanex Building Products'),
('NXE', 'Nexgen Energy Ltd. Common Shares'),
('NXPI', 'NXP Semiconductors N.V.'),
('NXT', 'Nextracker'),
('NYT', 'New York Times Company'),
('NZF', 'Nuveen Municipal Credit Income Fund'),
('O', 'Realty Income'),
('OBDC', 'Blue Owl Capital'),
('OBE', 'Obsidian Energy Ltd. Common Shares'),
('OC', 'Owens Corning Inc'),
('OCFC', 'OceanFirst Financial'),
('OCSL', 'Oaktree Specialty Lending'),
('OCUL', 'Ocular Therapeutix'),
('ODFL', 'Old Dominion Freight Line'),
('ODP', 'The ODP'),
('OEC', 'Orion S.A. Common Shares'),
('OGE', 'OGE Energy Corp'),
('OGN', 'Organon & Co.'),
('OGS', 'ONE Gas'),
('OHI', 'Omega Healthcare Investors'),
('OI', 'O-I Glass'),
('OII', 'Oceaneering International'),
('OIS', 'Oil States International'),
('OKE', 'ONEOK'),
('OKLO', 'Oklo'),
('OKTA', 'Okta'),
('OLMA', 'Olema Pharmaceuticals'),
('OLN', 'Olin'),
('OM', 'Outset Medical'),
('OMC', 'Omnicom Group'),
('OMF', 'OneMain Holdings'),
('OMI', 'Owens & Minor'),
('ON', 'ON Semiconductor'),
('ONB', 'Old National Bancorp'),
('ONDS', 'Ondas Holdings'),
('ONTO', 'Onto Innovation'),
('OPCH', 'Option Care Health'),
('OPEN', 'Opendoor Technologies Inc'),
('OPFI', 'OppFi'),
('OPRA', 'Opera Limited'),
('OPRT', 'Oportun Financial'),
('OPRX', 'OptimizeRx'),
('ORA', 'Ormat Technologies'),
('ORBS', 'Eightco Holdings'),
('ORC', 'Orchid Island Capital'),
('ORCL', 'Oracle'),
('ORI', 'Old Republic International'),
('ORIC', 'Oric Pharmaceuticals'),
('ORKA', 'Oruka Therapeutics'),
('ORLA', 'Orla Mining Ltd. Common Shares'),
('ORRF', 'Orrstown Financial Services'),
('OS', 'OneStream'),
('OSBC', 'Old Second Bancorp'),
('OSK', 'Oshkosh Corporation (Holding Company)Common Stock'),
('OSS', 'One Stop Systems'),
('OTEX', 'Open Text Corporation Common Shares'),
('OTF', 'Blue Owl Technology Finance'),
('OTIS', 'Otis Worldwide'),
('OUST', 'Ouster'),
('OUT', 'OUTFRONT Media'),
('OVV', 'Ovintiv Inc.'),
('OWL', 'Blue Owl Capital'),
('OWLS', 'OBOOK Holdings'),
('OXLC', 'Oxford Lane Capital'),
('OXM', 'Oxford Industries'),
('OXY', 'Occidental Petroleum'),
('OZK', 'Bank OZK'),
('PAAS', 'Pan American Silver'),
('PACK', 'Ranpak Holdings Corp'),
('PACS', 'PACS Group'),
('PAGS', 'PagSeguro Digital Ltd.'),
('PAM', 'Pampa Energia S.A.'),
('PANW', 'Palo Alto Networks'),
('PAR', 'Par Technology Corp'),
('PATH', 'UiPath'),
('PAX', 'Patria Investments Limited'),
('PAXS', 'PIMCO Access Income Fund Common Shares of Beneficial Interest'),
('PAY', 'Paymentus Holdings'),
('PAYC', 'Paycom Software'),
('PAYO', 'Payoneer Global'),
('PAYX', 'Paychex'),
('PB', 'Prosperity Bancshares'),
('PBA', 'Pembina Pipeline'),
('PBF', 'PBF Energy'),
('PBI', 'Pitney Bowes'),
('PBYI', 'Puma Biotechnology Inc'),
('PCAR', 'Paccar'),
('PCG', 'Pacific Gas & Electric Co.'),
('PCH', 'PotlatchDeltic'),
('PCN', 'Pimco Corporate & Income Strategy Fund'),
('PCRX', 'Pacira BioSciences'),
('PCT', 'PureCycle Technologies'),
('PCTY', 'Paylocity Holding'),
('PCVX', 'Vaxcyte'),
('PD', 'PagerDuty'),
('PDD', 'PDD Holdings'),
('PDI', 'PIMCO Dynamic Income Fund'),
('PDM', 'Piedmont Realty Trust'),
('PDO', 'PIMCO Dynamic Income Opportunities Fund Common Shares of Beneficial Interest'),
('PDYN', 'Palladyne AI'),
('PEB', 'Pebblebrook Hotel Trust Common Shares of Beneficial Interest'),
('PECO', 'Phillips Edison & Company'),
('PEG', 'Public Service Enterprise Group Incorporated'),
('PEGA', 'Pegasystems'),
('PEN', 'Penumbra'),
('PENG', 'Penguin Solutions'),
('PENN', 'PENN Entertainment'),
('PEP', 'PepsiCo'),
('PEPG', 'PepGen'),
('PFE', 'Pfizer'),
('PFG', 'Principal Financial Group Inc'),
('PFGC', 'Performance Food Group Company'),
('PFLT', 'PennantPark Floating Rate Capital Ltd.'),
('PFN', 'PIMCO Income Strategy Fund II'),
('PFS', 'Provident Financial Services Inc'),
('PFSI', 'PennyMac Financial Services'),
('PG', 'Procter & Gamble Company'),
('PGEN', 'Precigen'),
('PGNY', 'Progyny'),
('PGR', 'Progressive Corporation'),
('PGRE', 'Paramount Group'),
('PGY', 'Pagaya Technologies Ltd'),
('PH', 'Parker-Hannifin'),
('PHAT', 'Phathom Pharmaceuticals'),
('PHG', 'Koninklijke Philips N.V. NY Registry Shares'),
('PHIN', 'PHINIA'),
('PHM', 'PulteGroup'),
('PHR', 'Phreesia Inc'),
('PI', 'Impinj'),
('PII', 'Polaris'),
('PINC', 'Premier'),
('PINS', 'Pinterest'),
('PK', 'Park Hotels & Resorts'),
('PKG', 'Packaging Corporation of America'),
('PL', 'Planet Labs PBC'),
('PLAB', 'Photronics'),
('PLD', 'Prologis'),
('PLNT', 'Planet Fitness'),
('PLTR', 'Palantir Technologies'),
('PLYM', 'Plymouth Industrial REIT'),
('PM', 'Philip Morris International Inc'),
('PML', 'Pimco Municipal Income Fund II Common Shares of Beneficial Interest'),
('PMT', 'PennyMac Mortgage Investment Trust Common Shares of Beneficial Interest'),
('PNC', 'PNC Financial Services Group Inc.'),
('PNFP', 'Pinnacle Financial Partners'),
('PNNT', 'PennantPark Investment'),
('PNR', 'Pentair'),
('PNW', 'Pinnacle West'),
('PODD', 'Insulet'),
('POET', 'POET Technologies Inc. Common Shares'),
('PONY', 'Pony AI'),
('POOL', 'Pool'),
('POST', 'Post Holdings'),
('POWI', 'Power Integrations'),
('PPG', 'PPG Industries'),
('PPL', 'PPL'),
('PPTA', 'Perpetua Resources Corp. Common Shares'),
('PRA', 'ProAssurance'),
('PRAX', 'Praxis Precision Medicines'),
('PRCH', 'Porch Group'),
('PRCT', 'PROCEPT BioRobotics'),
('PRDO', 'Perdoceo Education'),
('PRG', 'PROG Holdings'),
('PRGO', 'Perrigo Company plc'),
('PRGS', 'Progress Software'),
('PRIM', 'Primoris Services'),
('PRM', 'Perimeter Solutions SA'),
('PRMB', 'Primo Brands'),
('PRME', 'Prime Medicine'),
('PRO', 'PROS Holdings'),
('PRTA', 'Prothena Corporation plc'),
('PRTH', 'Priority Technology Holdings'),
('PRU', 'Prudential Financial'),
('PRVA', 'Privia Health Group'),
('PSA', 'Public Storage'),
('PSIX', 'Power Solutions International'),
('PSKY', 'Paramount Skydance'),
('PSN', 'Parsons'),
('PSNL', 'Personalis'),
('PSO', 'Pearson Plc'),
('PSTG', 'Pure Storage'),
('PSX', 'Phillips 66'),
('PTC', 'PTC'),
('PTCT', 'PTC Therapeutics'),
('PTEN', 'Patterson-UTI Energy'),
('PTGX', 'Protagonist Therapeutics'),
('PTON', 'Peloton Interactive'),
('PTY', 'Pimco Corporate & Income Opportunity Fund'),
('PUBM', 'PubMatic'),
('PUK', 'Prudential Public Limited Company'),
('PUMP', 'ProPetro Holding'),
('PVH', 'PVH'),
('PWP', 'Perella Weinberg Partners'),
('PWR', 'Quanta Services'),
('PX', 'P10'),
('PXED', 'Phoenix Education Partners Inc'),
('PYPL', 'PayPal Holdings'),
('QBTS', 'D-Wave Quantum Inc. Common Shares'),
('QBTZ', 'Defiance Daily Target 2x Short QBTS ETF'),
('QCOM', 'QUALCOMM Incorporated'),
('QDEL', 'QuidelOrtho'),
('QFIN', 'Qfin Holdings'),
('QGEN', 'Qiagen N.V. Common Shares'),
('QH', 'Quhuo Limited American Depository Shares'),
('QMCO', 'Quantum'),
('QNST', 'QuinStreet'),
('QRVO', 'Qorvo'),
('QS', 'QuantumScape'),
('QTRX', 'Quanterix'),
('QTWO', 'Q2 Holdings'),
('QUBT', 'Quantum Computing'),
('QUBX', 'Tradr 2X Long QUBT Daily ETF'),
('QURE', 'uniQure N.V.'),
('QXO', 'QXO'),
('RACE', 'Ferrari N.V. Common Shares'),
('RAL', 'Ralliant'),
('RAMP', 'LiveRamp Holdings'),
('RAPP', 'Rapport Therapeutics'),
('RAPT', 'RAPT Therapeutics'),
('RARE', 'Ultragenyx Pharmaceutical'),
('RBA', 'RB Global'),
('RBLX', 'Roblox'),
('RBRK', 'Rubrik'),
('RCAT', 'Red Cat Holdings'),
('RCI', 'Rogers Communication'),
('RCL', 'Royal Caribbean Cruises Ltd.'),
('RCUS', 'Arcus Biosciences'),
('RDDT', 'Reddit'),
('RDN', 'Radian Group'),
('RDNT', 'RadNet'),
('RDTL', 'GraniteShares 2x Long RDDT Daily ETF'),
('REAL', 'The RealReal'),
('REG', 'Regency Centers'),
('REGN', 'Regeneron Pharmaceuticals'),
('RELX', 'RELX PLC PLC'),
('RELY', 'Remitly Global'),
('REPL', 'Replimune Group'),
('REVG', 'REV Group'),
('REYN', 'Reynolds Consumer Products'),
('REZI', 'Resideo Technologies'),
('RF', 'Regions Financial'),
('RGEN', 'Repligen'),
('RGLD', 'Royal Gold'),
('RGNX', 'REGENXBIO'),
('RGTI', 'Rigetti Computing'),
('RGTZ', 'Defiance Daily Target 2x Short RGTI ETF'),
('RH', 'RH'),
('RHI', 'Robert Half'),
('RHP', 'Ryman Hospitality Properties Inc.'),
('RIGL', 'Rigel Pharmaceuticals'),
('RIO', 'Rio Tinto Plc'),
('RIOT', 'Riot Platforms'),
('RITM', 'Rithm Capital'),
('RIVN', 'Rivian Automotive'),
('RJF', 'Raymond James Financial'),
('RKLB', 'Rocket Lab'),
('RKT', 'Rocket Companies'),
('RL', 'Ralph Lauren'),
('RLAY', 'Relay Therapeutics'),
('RLI', 'RLI'),
('RLJ', 'RLJ Lodging Trust Common Shares of Beneficial Interest $0.01 par value'),
('RMBS', 'Rambus'),
('RMD', 'ResMed'),
('RNA', 'Avidity Biosciences'),
('RNAC', 'Cartesian Therapeutics'),
('RNG', 'RingCentral'),
('RNST', 'Renasant'),
('ROCK', 'Gibraltar Industries'),
('ROIV', 'Roivant Sciences Ltd. Common Shares'),
('ROK', 'Rockwell Automation'),
('ROL', 'Rollins'),
('ROOT', 'Root'),
('ROP', 'Roper Technologies'),
('ROST', 'Ross Stores'),
('RPAY', 'Repay Holdings'),
('RPD', 'Rapid7'),
('RPM', 'RPM International'),
('RRC', 'Range Resources'),
('RRX', 'Regal Rexnord'),
('RS', 'Reliance'),
('RSG', 'Republic Services'),
('RSI', 'Rush Street Interactive'),
('RTO', 'Rentokil Initial plc'),
('RTX', 'RTX'),
('RUM', 'Rumble'),
('RUN', 'Sunrun'),
('RUSHA', 'Rush Enterprises'),
('RVLV', 'Revolve Group'),
('RVMD', 'Revolution Medicines'),
('RVTY', 'Revvity'),
('RWT', 'Redwood Trust'),
('RXO', 'RXO'),
('RXRX', 'Recursion Pharmaceuticals'),
('RXST', 'RxSight'),
('RY', 'Royal Bank Of Canada'),
('RYAAY', 'Ryanair Holdings plc'),
('RYAM', 'Rayonier Advanced Materials'),
('RYAN', 'Ryan Specialty Holdings'),
('RYN', 'Rayonier Inc. REIT'),
('RYTM', 'Rhythm Pharmaceuticals'),
('RZLT', 'Rezolute'),
('S', 'SentinelOne'),
('SA', 'Seabridge Gold'),
('SAH', 'Sonic Automotive'),
('SAIA', 'Saia'),
('SAIC', 'Science Applications International'),
('SAIL', 'SailPoint'),
('SAN', 'Banco Santander S.A. Sponsored ADR'),
('SANA', 'Sana Biotechnology'),
('SANM', 'Sanmina'),
('SAP', 'SAP SE ADS'),
('SARO', 'StandardAero'),
('SATL', 'Satellogic'),
('SATS', 'EchoStar'),
('SBAC', 'SBA Communications'),
('SBCF', 'Seacoast Banking Corporation of Florida'),
('SBET', 'SharpLink Gaming'),
('SBH', 'Sally Beauty Holdings Inc.'),
('SBLK', 'Star Bulk Carriers Corp. Common Shares'),
('SBRA', 'Sabra Health Care REIT'),
('SBS', 'Companhia de saneamento Basico Do Estado De Sao Paulo - Sabesp'),
('SBUX', 'Starbucks'),
('SCCO', 'Southern Copper'),
('SCE^K', 'Southern California Edison Company 5.45% Fixed-to-Floating Rate Trust Preference Securities'),
('SCHW', 'Charles Schwab Corporation'),
('SCI', 'Service Corporation International'),
('SCLX', 'Scilex Holding Company'),
('SCM', 'Stellus Capital Investment'),
('SCS', 'Steelcase'),
('SCVL', 'Shoe Carnival'),
('SDGR', 'Schrodinger Inc'),
('SDOW', 'ProShares UltraPro Short Dow30 -3x Shares'),
('SDRL', 'Seadrill Limited Common Shares'),
('SEDG', 'SolarEdge Technologies'),
('SEE', 'Sealed Air'),
('SEI', 'Solaris Energy Infrastructure'),
('SEIC', 'SEI Investments Company'),
('SEM', 'Select Medical Holdings'),
('SENS', 'Senseonics Holdings'),
('SEPN', 'Septerna'),
('SERV', 'Serve Robotics'),
('SEV', 'Aptera Motors'),
('SEZL', 'Sezzle'),
('SF', 'Stifel Financial'),
('SFD', 'Smithfield Foods'),
('SFL', 'SFL Corporation Ltd'),
('SFM', 'Sprouts Farmers Market'),
('SFNC', 'Simmons First National'),
('SG', 'Sweetgreen'),
('SGBX', 'Safe & Green Holdings Corp'),
('SGHC', 'Super Group (SGHC) Limited'),
('SGI', 'Somnigroup International'),
('SGML', 'Sigma Lithium Corporation Common Shares'),
('SGRY', 'Surgery Partners'),
('SHAK', 'Shake Shack'),
('SHC', 'Sotera Health Company'),
('SHEL', 'Shell PLC'),
('SHLS', 'Shoals Technologies Group'),
('SHO', 'Sunstone Hotel Investors Inc. Sunstone Hotel Investors Inc. Common Shares'),
('SHOO', 'Steven Madden Ltd.'),
('SHOP', 'Shopify'),
('SHW', 'Sherwin-Williams'),
('SIBN', 'SI-BONE'),
('SIG', 'Signet Jewelers Limited Common Shares'),
('SIGI', 'Selective Insurance Group'),
('SIMO', 'Silicon Motion Technology'),
('SIRI', 'SiriusXM Holdings'),
('SITC', 'SITE Centers'),
('SITE', 'SiteOne Landscape Supply'),
('SJM', 'The J.M. Smucker Company'),
('SKE', 'Skeena Resources Limited Common Shares'),
('SKM', 'SK Telecom Co. Ltd.'),
('SKT', 'Tanger'),
('SKWD', 'Skyward Specialty Insurance Group'),
('SKY', 'Champion Homes'),
('SKYT', 'SkyWater Technology'),
('SLB', 'SLB Limited Common Shares'),
('SLDB', 'Solid Biosciences'),
('SLDE', 'Slide Insurance Holdings'),
('SLDP', 'Solid Power'),
('SLG', 'SL Green Realty Corp'),
('SLGN', 'Silgan Holdings'),
('SLM', 'SLM'),
('SLNO', 'Soleno Therapeutics'),
('SLP', 'Simulations Plus'),
('SLRC', 'SLR Investment'),
('SLVM', 'Sylvamo'),
('SM', 'SM Energy Company'),
('SMA', 'SmartStop Self Storage REIT'),
('SMCI', 'Super Micro Computer'),
('SMCL', 'Smurfit Kappa'),
('SMFG', 'Sumitomo Mitsui Financial Group Inc Unsponsored'),
('SMG', 'Scotts Miracle-Gro Company'),
('SMLR', 'Semler Scientific Inc'),
('SMMT', 'Summit Therapeutics'),
('SMPL', 'The Simply Good Foods Company'),
('SMST', 'Safehold'),
('SMTC', 'Semtech'),
('SMX', 'SMX (Security Matters) Public Limited Company'),
('SN', 'SharkNinja'),
('SNA', 'Snap-on'),
('SNAP', 'Snap'),
('SNCY', 'Sun Country Airlines Holdings'),
('SNDK', 'Sandisk'),
('SNDL', 'SNDL Inc.'),
('SNDX', 'Syndax Pharmaceuticals'),
('SNEX', 'StoneX Group'),
('SNN', 'Smith & Nephew SNATS'),
('SNPS', 'Synopsys'),
('SNV', 'Synovus Financial'),
('SNX', 'TD SYNNEX'),
('SNY', 'Sanofi ADS'),
('SO', 'Southern Company'),
('SOBO', 'South Bow Corporation Common Shares'),
('SOC', 'Sable Offshore'),
('SOFI', 'SoFi Technologies'),
('SOFX', 'Defiance Daily Target 2X Long SOFI ETF'),
('SOLSV', 'Solstice Advanced Materials'),
('SOLT', '2x Solana ETF'),
('SOLV', 'Solventum'),
('SOLZ', 'Solana ETF'),
('SON', 'Sonoco Products Company'),
('SONN', 'Sonnet BioTherapeutics Holdings'),
('SONO', 'Sonos'),
('SONY', 'Sony Group'),
('SOUN', 'SoundHound AI Inc'),
('SPAI', 'Safe Pro Group'),
('SPG', 'Simon Property Group'),
('SPGI', 'S&P Global'),
('SPNS', 'Sapiens International Corporation N.V. Common Shares'),
('SPNT', 'SiriusPoint Ltd. Common Shares'),
('SPOT', 'Spotify Technology S.A.'),
('SPRB', 'Spruce Biosciences'),
('SPRY', 'ARS Pharmaceuticals'),
('SPSC', 'SPS Commerce'),
('SPT', 'Sprout Social Inc'),
('SPXC', 'SPX Technologies'),
('SPXS', 'Direxion Daily S&P 500 Bear -3X Shares'),
('SQM', 'Sociedad Quimica y Minera S.A.'),
('SQNS', 'Sequans Communications S.A.'),
('SRE', 'DBA Sempra'),
('SRFM', 'Surf Air Mobility'),
('SRPT', 'Sarepta Therapeutics'),
('SRRK', 'Scholar Rock Holding'),
('SRTA', 'Strata Critical Medical'),
('SSB', 'SouthState Bank'),
('SSK', 'REX-Osprey SOL + Staking ETF'),
('SSL', 'Sasol Ltd.'),
('SSNC', 'SS&C Technologies Holdings'),
('SSRM', 'SSR Mining'),
('SSYS', 'Stratasys Ltd.'),
('ST', 'Sensata Technologies Holding plc'),
('STAA', 'STAAR Surgical Company'),
('STAG', 'Stag Industrial'),
('STE', 'STERIS plc'),
('STEM', 'Stem'),
('STEP', 'StepStone Group'),
('STI', 'Solidion Technology'),
('STKL', 'SunOpta'),
('STLA', 'Stellantis N.V. Common Shares'),
('STLD', 'Steel Dynamics'),
('STM', 'STMicroelectronics N.V.'),
('STNE', 'StoneCo Ltd.'),
('STNG', 'Scorpio Tankers Inc. Common Shares'),
('STOK', 'Stoke Therapeutics'),
('STRL', 'Sterling Infrastructure'),
('STT', 'State Street'),
('STUB', 'StubHub Holdings'),
('STWD', 'STARWOOD PROPERTY TRUST INC. Starwood Property Trust'),
('STX', 'Seagate Technology Holdings PLC'),
('STZ', 'Constellation Brands'),
('SUI', 'Sun Communities'),
('SUPN', 'Supernus Pharmaceuticals'),
('SUPV', 'Grupo Supervielle S.A.'),
('SUPX', 'SuperX AI Technology Limited'),
('SUZ', 'Suzano S.A.'),
('SVIX', '1x Short VIX Futures ETF'),
('SVM', 'Silvercorp Metals Inc. Common Shares'),
('SVV', 'Savers Value Village'),
('SVXY', 'ProShares Short VIX Short-Term Futures ETF -1x Shares'),
('SW', 'Smurfit WestRock'),
('SWBI', 'Smith & Wesson Brands'),
('SWK', 'Stanley Black & Decker'),
('SWKS', 'Skyworks Solutions'),
('SXC', 'SunCoke Energy'),
('SXT', 'Sensient Technologies'),
('SYF', 'Synchrony Financial'),
('SYK', 'Stryker'),
('SYM', 'Symbotic'),
('SYRE', 'Spyre Therapeutics'),
('SYY', 'Sysco'),
('T', 'AT&T'),
('TAC', 'TransAlta'),
('TAK', 'Takeda Pharmaceutical Company Limited'),
('TAL', 'TAL Education Group'),
('TALO', 'Talos Energy'),
('TAOX', 'Tao Synergies'),
('TAP', 'Molson Coors Beverage Company'),
('TARA', 'Protara Therapeutics'),
('TARS', 'Tarsus Pharmaceuticals'),
('TASK', 'TaskUs'),
('TBBB', 'BBB Foods'),
('TBBK', 'The Bancorp Inc'),
('TCBI', 'Texas Capital Bancshares'),
('TCOM', 'Trip.com Group Limited'),
('TCPC', 'BlackRock TCP Capital'),
('TD', 'Toronto Dominion Bank'),
('TDC', 'Teradata'),
('TDG', 'TransDigm Group'),
('TDOC', 'Teladoc Health'),
('TDS', 'Telephone and Data Systems Inc. Common Shares'),
('TDUP', 'ThredUp'),
('TDW', 'Tidewater Inc'),
('TDY', 'Teledyne Technologies Incorporated'),
('TEAM', 'Atlassian'),
('TECH', 'Bio-Techne Corp'),
('TECK', 'Teck Resources Ltd'),
('TECS', 'Direxion Daily Technology Bear -3X Shares'),
('TECX', 'Tectonic Therapeutic'),
('TEF', 'Telefonica SA'),
('TEL', 'TE Connectivity plc'),
('TEM', 'Tempus AI'),
('TENB', 'Tenable Holdings'),
('TEO', 'Telecom Argentina SA'),
('TER', 'Teradyne'),
('TERN', 'Terns Pharmaceuticals'),
('TETH', '21Shares Ethereum ETF'),
('TEVA', 'Teva Pharmaceutical Industries Limited'),
('TEX', 'Terex'),
('TFC', 'Truist Financial'),
('TFPM', 'Triple Flag Precious Metals Corp. Common Shares'),
('TFSL', 'TFS Financial'),
('TFX', 'Teleflex Incorporated'),
('TGEN', 'Tecogen'),
('TGNA', 'TEGNA Inc'),
('TGS', 'Transportadora de Gas del Sur SA TGS'),
('TGT', 'Target'),
('TGTX', 'TG Therapeutics'),
('TH', 'Target Hospitality'),
('THC', 'Tenet Healthcare'),
('THO', 'Thor Industries'),
('THS', 'Treehouse Foods'),
('TIC', 'TIC Solutions'),
('TIGO', 'Millicom International Cellular S.A.'),
('TIMB', 'TIM S.A.'),
('TJX', 'TJX Companies Inc.'),
('TK', 'Teekay Corporation Ltd.'),
('TKC', 'Turkcell Iletisim Hizmetleri AS'),
('TKO', 'TKO Group Holdings'),
('TLN', 'Talen Energy'),
('TLS', 'Telos'),
('TM', 'Toyota Motor'),
('TMC', 'TMC the metals company'),
('TMDX', 'TransMedics Group'),
('TMHC', 'Taylor Morrison Home'),
('TMO', 'Thermo Fisher Scientific Inc'),
('TMUS', 'T-Mobile US'),
('TNDM', 'Tandem Diabetes Care'),
('TNET', 'TriNet Group'),
('TNGX', 'Tango Therapeutics'),
('TNK', 'Teekay Tankers Ltd.'),
('TNL', 'Travel Leisure Co. Common Stock'),
('TNXP', 'Tonix Pharmaceuticals Holding'),
('TOL', 'Toll Brothers'),
('TOST', 'Toast'),
('TPC', 'Tutor Perini'),
('TPG', 'TPG'),
('TPH', 'Tri Pointe Homes'),
('TPL', 'Texas Pacific Land Corporation'),
('TPR', 'Tapestry, Inc.'),
('TRDA', 'Entrada Therapeutics'),
('TREX', 'Trex Company'),
('TRGP', 'Targa Resources'),
('TRI', 'Thomson Reuters Corporation Common Shares'),
('TRIN', 'Trinity Capital'),
('TRIP', 'TripAdvisor'),
('TRMB', 'Trimble'),
('TRMD', 'TORM plc'),
('TRML', 'Tourmaline Bio'),
('TRNO', 'Terreno Realty'),
('TROW', 'T. Rowe Price'),
('TRP', 'TC Energy'),
('TRS', 'TriMas'),
('TRTX', 'TPG RE Finance Trust'),
('TRV', 'The Travelers Companies'),
('TRVI', 'Trevi Therapeutics'),
('TS', 'Tenaris S.A.'),
('TSCO', 'Tractor Supply Company'),
('TSDD', 'GraniteShares 2x Short TSLA Daily ETF'),
('TSEM', 'Tower Semiconductor Ltd.'),
('TSLA', 'Tesla'),
('TSLL', 'Direxion Daily TSLA Bull 2X Shares'),
('TSLX', 'Sixth Street Specialty Lending'),
('TSM', 'Taiwan Semiconductor Manufacturing Company Ltd.'),
('TSN', 'Tyson Foods'),
('TSSI', 'TSS'),
('TT', 'Trane Technologies plc'),
('TTAN', 'ServiceTitan'),
('TTC', 'Toro Company'),
('TTD', 'The Trade Desk'),
('TTE', 'TotalEnergies SE'),
('TTEK', 'Tetra Tech'),
('TTGT', 'TechTarget'),
('TTI', 'Tetra Technologies'),
('TTMI', 'TTM Technologies'),
('TTRX', 'Turn Therapeutics Inc'),
('TTWO', 'Take-Two Interactive Software'),
('TVTX', 'Travere Therapeutics'),
('TWI', 'Titan International Inc.'),
('TWLO', 'Twilio'),
('TWO', 'Two Harbors Investment Corp'),
('TWST', 'Twist Bioscience'),
('TX', 'Ternium S.A. Ternium S.A.'),
('TXG', '10x Genomics'),
('TXN', 'Texas Instruments Incorporated'),
('TXNM', 'TXNM Energy'),
('TXRH', 'Texas Roadhouse'),
('TXT', 'Textron'),
('TYL', 'Tyler Technologies'),
('TYRA', 'Tyra Biosciences'),
('U', 'Unity Software Inc'),
('UAL', 'United Airlines Holdings'),
('UBER', 'Uber'),
('UBS', 'UBS Group AG Registered'),
('UCTT', 'Ultra Clean Holdings'),
('UDMY', 'Udemy'),
('UDR', 'UDR, Inc.'),
('UE', 'Urban Edge Properties Common Shares of Beneficial Interest'),
('UEC', 'Uranium Energy'),
('UFPI', 'UFP Industries'),
('UGI', 'UGI'),
('UHS', 'Universal Health Services'),
('UL', 'Unilever PLC'),
('ULS', 'UL Solutions'),
('ULTA', 'Ulta Beauty'),
('UMAC', 'Unusual Machines'),
('UMBF', 'UMB Financial'),
('UMH', 'UMH Properties'),
('UNCY', 'Unicycive Therapeutics'),
('UNH', 'UnitedHealth Group'),
('UNM', 'Unum Group'),
('UNP', 'Union Pacific'),
('UPB', 'Upstream Bio'),
('UPBD', 'Upbound Group'),
('UPS', 'United Parcel Service'),
('UPST', 'Upstart Holdings'),
('UPSX', 'Tradr 2X Long UPST Daily ETF'),
('UPWK', 'Upwork'),
('URBN', 'Urban Outfitters'),
('URGN', 'UroGen Pharma Ltd.'),
('URI', 'United Rentals'),
('USA', 'Liberty All-Star Equity Fund'),
('USAR', 'USA Rare Earth'),
('USB', 'U.S. Bancorp'),
('USFD', 'US Foods Holding'),
('USNA', 'USANA Health Sciences'),
('UTF', 'Cohen & Steers Infrastructure Fund Inc'),
('UTG', 'Reaves Utility Income Fund Common Shares of Beneficial Interest'),
('UTI', 'Universal Technical Institute Inc'),
('UTZ', 'Utz Brands Inc'),
('UUUU', 'Energy Fuels'),
('UVE', 'UNIVERSAL INSURANCE HOLDINGS INC'),
('UWMC', 'UWM Holdings'),
('V', 'Visa'),
('VAC', 'Marriott Vacations Worldwide'),
('VAL', 'Valaris Limited Common Shares'),
('VALE', 'VALE S.A.'),
('VC', 'Visteon'),
('VCEL', 'Vericel'),
('VCYT', 'Veracyte'),
('VECO', 'Veeco Instruments'),
('VEEV', 'Veeva Systems'),
('VELO', 'Velo3D'),
('VERA', 'Vera Therapeutics'),
('VERI', 'Veritone'),
('VERX', 'Vertex'),
('VET', 'Vermilion Energy Inc. Common'),
('VFC', 'V.F.'),
('VG', 'Venture Global'),
('VIA', 'Via Transportation Inc'),
('VIAV', 'Viavi Solutions'),
('VICI', 'VICI Properties'),
('VIK', 'Viking Holdings Ltd'),
('VIPS', 'Vipshop Holdings Limited'),
('VIRT', 'Virtu Financial'),
('VIST', 'Vista Energy S.A.B. de C.V.'),
('VITL', 'Vital Farms'),
('VIV', 'Telefonica Brasil S.A.'),
('VKTX', 'Viking Therapeutics'),
('VLO', 'Valero Energy'),
('VLRS', 'Controladora Vuela Compania de Aviacion S.A.B. de C.V.'),
('VLTO', 'Veralto Corp'),
('VLY', 'Valley National Bancorp'),
('VMC', 'Vulcan Materials Company'),
('VMEO', 'Vimeo'),
('VNDA', 'Vanda Pharmaceuticals'),
('VNET', 'VNET Group'),
('VNO', 'Vornado Realty Trust'),
('VNOM', 'Viper Energy'),
('VNT', 'Vontier'),
('VOD', 'Vodafone Group Plc'),
('VOYA', 'Voya Financial'),
('VOYG', 'Voyager Technologies'),
('VRDN', 'Viridian Therapeutics'),
('VRE', 'Veris Residential'),
('VRNS', 'Varonis Systems'),
('VRNT', 'Verint Systems'),
('VRRM', 'Verra Mobility'),
('VRSK', 'Verisk Analytics'),
('VRSN', 'VeriSign'),
('VRT', 'Vertiv Holdings LLC'),
('VRTX', 'Vertex Pharmaceuticals Incorporated'),
('VSAT', 'ViaSat'),
('VSCO', 'Victorias Secret & Co.'),
('VSH', 'Vishay Intertechnology'),
('VST', 'Vistra'),
('VSTM', 'Verastem'),
('VSTS', 'Vestis'),
('VTLE', 'Vital Energy'),
('VTR', 'Ventas'),
('VTRS', 'Viatris'),
('VTS', 'Vitesse Energy'),
('VTYX', 'Ventyx Biosciences'),
('VVV', 'Valvoline'),
('VVX', 'V2X'),
('VWAV', 'VisionWave Holdings'),
('VYX', 'NCR Voyix'),
('VZ', 'Verizon Communications'),
('WAB', 'Westinghouse Air Brake Technologies'),
('WAFD', 'WaFd'),
('WAL', 'Western Alliance Bancorporation'),
('WAT', 'Waters'),
('WAY', 'Waystar Holding'),
('WB', 'Weibo'),
('WBA', 'Walgreens Boots Alliance'),
('WBD', 'Warner Bros. Discovery'),
('WBI', 'WaterBridge Infrastructure LLC'),
('WBS', 'Webster Financial'),
('WCC', 'WESCO International'),
('WCN', 'Waste Connections Inc. Common Shares'),
('WDAY', 'Workday'),
('WDC', 'Western Digital'),
('WDS', 'Woodside Energy Group Limited'),
('WEAV', 'Weave Communications'),
('WEC', 'WEC Energy Group'),
('WELL', 'Welltower'),
('WERN', 'Werner Enterprises'),
('WEST', 'Westrock Coffee Company'),
('WEX', 'WEX'),
('WFC', 'Wells Fargo & Company'),
('WFRD', 'Weatherford International plc'),
('WGO', 'Winnebago Industries'),
('WGS', 'GeneDx Holdings'),
('WH', 'Wyndham Hotels & Resorts'),
('WHD', 'Cactus'),
('WING', 'Wingstop'),
('WIX', 'Wix.com Ltd.'),
('WK', 'Workiva'),
('WKC', 'World Kinect'),
('WKEY', 'WISeKey International Holding Ltd'),
('WLK', 'Westlake'),
('WLY', 'John Wiley & Sons'),
('WM', 'Waste Management'),
('WMB', 'Williams Companies Inc.'),
('WMG', 'Warner Music Group'),
('WMS', 'Advanced Drainage Systems'),
('WMT', 'Walmart'),
('WNC', 'Wabash National'),
('WOLF', 'Wolfspeed'),
('WPC', 'W. P. Carey Inc. REIT'),
('WPM', 'Wheaton Precious Metals Corp Common Shares'),
('WPP', 'WPP plc'),
('WRB', 'W.R. Berkley'),
('WRBY', 'Warby Parker'),
('WRD', 'WeRide'),
('WSBC', 'WesBanco'),
('WSC', 'WillScot Holdings'),
('WSFS', 'WSFS Financial'),
('WSM', 'Williams-Sonoma'),
('WSO', 'Watsco'),
('WST', 'West Pharmaceutical Services'),
('WT', 'WisdomTree'),
('WTFC', 'Wintrust Financial'),
('WTRG', 'Essential Utilities'),
('WTW', 'Willis Towers Watson'),
('WULF', 'TeraWulf'),
('WVE', 'Wave Life Sciences Ltd.'),
('WWD', 'Woodward'),
('WY', 'Weyerhaeuser Company'),
('WYFI', 'WhiteFiber'),
('WYNN', 'Wynn Resorts Limited'),
('XEL', 'Xcel Energy'),
('XELLL', 'Xcel Energy Inc. 6.25% Junior Subordinated Notes Series due 2085'),
('XENE', 'Xenon Pharmaceuticals Inc. Common Shares'),
('XERS', 'Xeris Biopharma Holdings'),
('XMTR', 'Xometry Inc'),
('XNET', 'Xunlei Limited'),
('XOM', 'Exxon Mobil'),
('XP', 'XP'),
('XPEV', 'XPeng'),
('XPO', 'XPO'),
('XPOF', 'Xponential Fitness'),
('XPRO', 'Expro Group Holdings N.V.'),
('XRAY', 'DENTSPLY SIRONA'),
('XRPT', 'Volatility Shares Trust XRP 2X ETF'),
('XXRP', 'Teucrium 2x Long Daily XRP ETF'),
('XYL', 'Xylem'),
('XYZ', 'Block'),
('YANG', 'Direxion Daily FTSE China Bear -3X Shares'),
('YELP', 'Yelp'),
('YETI', 'YETI Holdings'),
('YEXT', 'Yext'),
('YINN', 'Direxion Daily FTSE China Bull 3X Shares'),
('YOU', 'Clear Secure Inc'),
('YPF', 'YPF Sociedad Anonima'),
('YUM', 'Yum! Brands'),
('YUMC', 'Yum China Holdings'),
('Z', 'Zillow Group'),
('ZBH', 'Zimmer Biomet Holdings'),
('ZBIO', 'Zenas BioPharma'),
('ZBRA', 'Zebra Technologies'),
('ZD', 'Ziff Davis'),
('ZETA', 'Zeta Global Holdings'),
('ZG', 'Zillow Group'),
('ZGN', 'Ermenegildo Zegna N.V.'),
('ZIM', 'ZIM Integrated Shipping Services Ltd.'),
('ZION', 'Zions Bancorporation N.A.'),
('ZK', 'ZEEKR Intelligent Technology Holding Limited'),
('ZLAB', 'Zai Lab Limited'),
('ZM', 'Zoom Communications'),
('ZS', 'Zscaler'),
('ZTO', 'ZTO Express'),
('ZTS', 'Zoetis'),
('ZVRA', 'Zevra Therapeutics'),
('ZWS', 'Zurn Elkay Water Solutions'),
('ZYME', 'Zymeworks');
