use StockPxLabs;
-- Drop tables if they exist (in correct order - child tables first, then parents)
DROP TABLE IF EXISTS user_trades;
DROP TABLE IF EXISTS user_usage;
DROP TABLE IF EXISTS user_preferences;
DROP TABLE IF EXISTS stock_performance_metrics;
DROP TABLE IF EXISTS daily_stock_data;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS stock_symbols;
DROP TABLE IF EXISTS roles;

-- Create roles table
CREATE TABLE IF NOT EXISTS roles (
    id INT AUTO_INCREMENT PRIMARY KEY,
    role_name VARCHAR(50) NOT NULL UNIQUE,
    display_name VARCHAR(100) NOT NULL,
    description TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_role_name (role_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Insert default roles (ignore if they already exist)
INSERT IGNORE INTO roles (role_name, display_name, description) VALUES
('free', 'Free Tier', 'Basic access with limited features'),
('pro', 'Pro', 'Full access to all trading analysis features'),
('enterprise', 'Enterprise', 'Advanced features with priority support'),
('admin', 'Admin', 'Full system administration access');

-- Create stock_symbols table (no dependencies)
CREATE TABLE IF NOT EXISTS stock_symbols (
    id INT AUTO_INCREMENT PRIMARY KEY,
    symbol VARCHAR(10) UNIQUE NOT NULL,
    company_name VARCHAR(255),
    INDEX idx_symbol (symbol)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Create users table (depends on roles)
CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role_id INT NOT NULL DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_login TIMESTAMP NULL,
    is_active BOOLEAN DEFAULT TRUE,
    email_verified BOOLEAN DEFAULT FALSE,
    verification_token VARCHAR(255) NULL,
    verification_token_expires TIMESTAMP NULL,
    FOREIGN KEY (role_id) REFERENCES roles(id),
    INDEX idx_email (email),
    INDEX idx_active (is_active),
    INDEX idx_role_id (role_id),
    INDEX idx_verification_token (verification_token)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Create user_preferences table (depends on users)
CREATE TABLE IF NOT EXISTS user_preferences (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    name VARCHAR(100) NOT NULL,
    default_days INT DEFAULT 365,
    default_atr_period INT DEFAULT 14,
    default_fast_ma INT DEFAULT 21,
    default_slow_ma INT DEFAULT 50,
    default_ma_type VARCHAR(10) DEFAULT 'ema',
    default_initial_capital DECIMAL(15,2) DEFAULT 100000.00,
    mean_reversion_threshold DECIMAL(5,2) DEFAULT 10.0,
    position_sizing_long DECIMAL(5,2) DEFAULT 5.0,
    position_sizing_short DECIMAL(5,2) DEFAULT 3.0,
    atr_multiplier_long DECIMAL(3,1) DEFAULT 2.0,
    atr_multiplier_short DECIMAL(3,1) DEFAULT 1.5,
    trades_columns JSON,
    favorite_stocks JSON DEFAULT NULL,
    subscription_tier VARCHAR(20) DEFAULT 'basic',
    trial_ends_at DATETIME NULL,
    subscription_status ENUM('trial', 'active', 'cancelled', 'expired') DEFAULT 'trial',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    INDEX idx_user_id (user_id),
    INDEX idx_subscription_tier (subscription_tier),
    INDEX idx_subscription_status (subscription_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Create daily_stock_data table (depends on stock_symbols)
CREATE TABLE IF NOT EXISTS daily_stock_data (
    id INT AUTO_INCREMENT PRIMARY KEY,
    symbol_id INT NOT NULL,
    date DATE NOT NULL,
    open DECIMAL(10,2),
    high DECIMAL(10,2),
    low DECIMAL(10,2),
    close DECIMAL(10,2),
    volume BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (symbol_id) REFERENCES stock_symbols(id) ON DELETE CASCADE,
    UNIQUE KEY unique_symbol_date (symbol_id, date),
    INDEX idx_symbol_id (symbol_id),
    INDEX idx_date (date),
    INDEX idx_symbol_date (symbol_id, date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Create stock_performance_metrics table (depends on stock_symbols)
CREATE TABLE IF NOT EXISTS stock_performance_metrics (
    id INT AUTO_INCREMENT PRIMARY KEY,
    symbol_id INT NOT NULL,
    analysis_date DATE NOT NULL,
    time_period VARCHAR(10) NOT NULL DEFAULT 'ALL',
    strategy_mode VARCHAR(10) NOT NULL DEFAULT 'long',
    total_return_pct DECIMAL(8,2),
    total_pnl DECIMAL(15,2),
    win_rate DECIMAL(5,2),
    total_trades INT,
    long_trades INT DEFAULT 0,
    short_trades INT DEFAULT 0,
    sharpe_ratio DECIMAL(8,2),
    analysis_params JSON,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (symbol_id) REFERENCES stock_symbols(id) ON DELETE CASCADE,
    UNIQUE KEY unique_symbol_analysis (symbol_id, analysis_date, time_period, strategy_mode),
    INDEX idx_symbol_analysis_date (symbol_id, analysis_date),
    INDEX idx_analysis_date (analysis_date),
    INDEX idx_time_period (time_period),
    INDEX idx_strategy_mode (strategy_mode),
    INDEX idx_total_return (total_return_pct),
    INDEX idx_sharpe_ratio (sharpe_ratio)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Create user_usage table for tracking monthly quotas (depends on users)
CREATE TABLE IF NOT EXISTS user_usage (
    user_id INT NOT NULL,
    month DATE NOT NULL,
    trades_count INT DEFAULT 0,
    ema_analyses_count INT DEFAULT 0,
    ma_optimizations_count INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, month),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    INDEX idx_month (month)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Create user_trades table (depends on users)
CREATE TABLE IF NOT EXISTS user_trades (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    symbol VARCHAR(10) NOT NULL,
    position_type ENUM('long', 'short') DEFAULT 'long',
    entry_date DATE NOT NULL,
    entry_price DECIMAL(10,2) NOT NULL,
    shares INT NOT NULL,
    exit_date DATE NULL,
    exit_price DECIMAL(10,2) NULL,
    stop_loss DECIMAL(10,2) NULL,
    target_price DECIMAL(10,2) NULL,
    trade_notes TEXT NULL,
    status ENUM('open', 'closed') DEFAULT 'open',
    pnl DECIMAL(15,2) NULL,
    pnl_percent DECIMAL(8,2) NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    INDEX idx_user_id (user_id),
    INDEX idx_symbol (symbol),
    INDEX idx_status (status),
    INDEX idx_position_type (position_type),
    INDEX idx_entry_date (entry_date),
    INDEX idx_user_symbol (user_id, symbol)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Insert stock symbols (S&P 500 + Additional stocks)
INSERT IGNORE INTO stock_symbols (symbol, company_name) VALUES
('A', 'Agilent Technologies'),
('AA', 'Alcoa Corporation'),
('AAPL', 'Apple Inc.'),
('ABBV', 'AbbVie'),
('ABNB', 'Airbnb'),
<<<<<<< HEAD
('ABT', 'Abbott Laboratories');
=======
('ABT', 'Abbott Laboratories'),
--#('ACGL', 'Arch Capital Group'),
--#('ACHR', 'Archer Aviation'),
--#('ACIW', 'ACI Worldwide Inc'),
--#('ACLS', 'Axcelis Technologies'),
--#('ACN', 'Accenture'),
--#('ADBE', 'Adobe Inc.'),
--#('ADI', 'Analog Devices'),
--#('ADM', 'Archer Daniels Midland'),
--#('ADP', 'Automatic Data Processing'),
--#('ADPT', 'Adaptive Biotechnologies'),
--#('ADSK', 'Autodesk'),
--#('ADT', 'ADT Inc.'),
--#('AEE', 'Ameren'),
--#('AEHR', 'Aehr Test Systems'),
--#('AEP', 'American Electric Power'),
--#('AES', 'AES Corporation'),
--#('AFL', 'Aflac'),
--#('AIG', 'American International Group'),
--#('AIRO', 'AIRO Group Holdings Inc'),
--#('AIZ', 'Assurant'),
--#('AJG', 'Arthur J. Gallagher & Co.'),
--#('AKAM', 'Akamai Technologies'),
--#('ALB', 'Albemarle Corporation'),
--#('ALGM', 'Allegro MicroSystems'),
--#('ALGN', 'Align Technology'),
--#('ALGT', 'Allegiant Travel'),
--#('ALH', 'Alliance Laundry Holdings Inc'),
--#('ALK', 'Alaska Air Group'),
--#('ALL', 'Allstate'),
--#('ALLE', 'Allegion'),
--#('ALLY', 'Ally Financial'),
--#('AMAT', 'Applied Materials'),
--#('AMCR', 'Amcor'),
--#('AMD', 'Advanced Micro Devices'),
--#('AME', 'Ametek'),
--#('AMGN', 'Amgen'),
--#('AMP', 'Ameriprise Financial'),
--#('AMPX', 'Amprius Technologies'),
--#('AMRC', 'Ameresco'),
--#('AMT', 'American Tower'),
--#('AMZN', 'Amazon'),
--#('AMZU', 'Direxion Daily AMZN Bull 2X Shares'),
--#('ANET', 'Arista Networks'),
--#('ANGX', 'Angel Studios Inc'),
--#('AON', 'Aon'),
--#('AOS', 'A. O. Smith'),
--#('APA', 'APA Corporation'),
--#('APD', 'Air Products'),
--#('APH', 'Amphenol'),
--#('APLD', 'Applied Digital'),
--#('APLS', 'Apellis Pharmaceuticals Inc'),
--#('APO', 'Apollo Global Management'),
--#('APPN', 'Appian'),
--#('APTV', 'Aptiv'),
--#('AR', 'Antero Resources'),
--#('ARE', 'Alexandria Real Estate Equities'),
--#('ARKB', 'ARK 21Shares Bitcoin ETF Beneficial Interest'),
--#('ARKX', 'ARK Space Exploration ETF'),
--#('ARMN', 'Aetherium Acquisition'),
--#('ASGN', 'ASGN Incorporated'),
--#('ASH', 'Ashland Global'),
--#('ASPI', 'ASP Isotopes'),
--#('ATMU', 'Atmus Filtration Technologies'),
--#('ATO', 'Atmos Energy'),
--#('AUB', 'Atlantic Union Bankshares Corp'),
--#('AVB', 'AvalonBay Communities'),
--#('AVGO', 'Broadcom'),
--#('AVY', 'Avery Dennison'),
--#('AWK', 'American Water Works'),
--#('AXON', 'Axon Enterprise'),
--#('AXP', 'American Express'),
--#('AZO', 'AutoZone'),
--#('BA', 'Boeing'),
--#('BAC', 'Bank of America'),
--#('BALL', 'Ball Corporation'),
--#('BAX', 'Baxter International'),
--#('BBIO', 'BridgeBio Pharma'),
--#('BBNX', 'Beta Bionics Inc'),
--#('BBWI', 'Bath & Body Works'),
--#('BBY', 'Best Buy'),
--#('BDX', 'Becton Dickinson'),
--#('BEN', 'Franklin Resources'),
--#('BF-B', 'Brown–Forman'),
--#('BG', 'Bunge Global'),
--#('BHF', 'Brighthouse Financial'),
--#('BIIB', 'Biogen'),
--#('BINI', 'Bollinger Innovations Inc'),
--#('BITU', 'ProShares Ultra Bitcoin ETF'),
--#('BITX', '2x Bitcoin Strategy ETF'),
--#('BJRI', 'BJ''s Restaurant Inc'),
--#('BK', 'BNY Mellon'),
--#('BKKT', 'Bakkt Holdings'),
--#('BKNG', 'Booking Holdings'),
--#('BKR', 'Baker Hughes'),
--#('BKSY', 'BlackSky Technology'),
--#('BKU', 'BankUnited Inc'),
--#('BL', 'BlackLine'),
--#('BLDR', 'Builders FirstSource'),
--#('BLK', 'BlackRock'),
--#('BLKB', 'Blackbaud'),
--#('BMNR', 'BitMine Immersion Technologies Inc'),
--#('BMNU', 'T-REX 2X Long BMNR Daily Target ETF'),
--#('BMY', 'Bristol Myers Squibb'),
--#('BNC', 'CEA Industries Inc'),
--#('BOIL', 'ProShares Ultra Bloomberg Natural Gas 2x Shares'),
--#('BR', 'Broadridge Financial Solutions'),
--#('BRBR', 'BellRing Brands'),
--#('BRCB', 'Black Rock Coffee Bar Inc'),
--#('BRK-B', 'Berkshire Hathaway'),
--#('BRO', 'Brown & Brown'),
--#('BRZE', 'Braze Inc'),
--#('BSX', 'Boston Scientific'),
--#('BTC', 'Grayscale Bitcoin Mini Trust ETF'),
--#('BTM', 'Bitcoin Depot'),
--#('BWIN', 'Baldwin Insurance Group'),
--#('BX', 'Blackstone Inc.'),
--#('BXP', 'BXP, Inc.'),
--#('BYRN', 'Byrna Technologies Inc'),
--#('C', 'Citigroup'),
--#('CADE', 'Cadence Bank'),
--#('CAG', 'Conagra Brands'),
--#('CAH', 'Cardinal Health'),
--#('CAI', 'Caris Life Sciences Inc'),
--#('CARG', 'CarGurus'),
--#('CARR', 'Carrier Global'),
--#('CART', 'Maplebear (Instacart)'),
--#('CAT', 'Caterpillar Inc.'),
--#('CB', 'Chubb Limited'),
--#('CBOE', 'Cboe Global Markets'),
--#('CBRE', 'CBRE Group'),
--#('CBRL', 'Cracker Barrel'),
--#('CCI', 'Crown Castle'),
--#('CCL', 'Carnival'),
--#('CCUP', 'T-REX 2X Long CRCL Daily Target ETF'),
--#('CDNS', 'Cadence Design Systems'),
--#('CDW', 'CDW'),
--#('CE', 'Celanese'),
--#('CEG', 'Constellation Energy'),
--#('CF', 'CF Industries'),
--#('CFG', 'Citizens Financial Group'),
--#('CGNX', 'Cognex'),
--#('CHD', 'Church & Dwight'),
--#('CHRW', 'C.H. Robinson'),
--#('CHTR', 'Charter Communications'),
--#('CHWY', 'Chewy Inc'),
--#('CHYM', 'Chimerix'),
--#('CI', 'Cigna'),
--#('CINF', 'Cincinnati Financial'),
--#('CIVI', 'Civitas Resources'),
--#('CL', 'Colgate-Palmolive'),
--#('CLX', 'Clorox'),
--#('CMCSA', 'Comcast'),
--#('CME', 'CME Group'),
--#('CMG', 'Chipotle Mexican Grill'),
--#('CMI', 'Cummins'),
--#('CMS', 'CMS Energy'),
--#('CNC', 'Centene Corporation'),
--#('CNM', 'Core & Main'),
--#('CNP', 'CenterPoint Energy'),
--#('CNXC', 'Concentrix'),
--#('COF', 'Capital One'),
--#('COIN', 'Coinbase Global'),
--#('CONI', 'GraniteShares 2x Short COIN Daily ETF'),
--#('COO', 'Cooper Companies (The)'),
--#('COP', 'ConocoPhillips'),
--#('COR', 'Cencora'),
--#('CORZ', 'Core Scientific'),
--#('COST', 'Costco'),
--#('CPAY', 'Corpay'),
--#('CPB', 'Campbell Soup Company'),
--#('CPRT', 'Copart'),
--#('CPS', 'Cooper-Standard Holdings'),
--#('CPT', 'Camden Property Trust'),
--#('CRC', 'California Resources'),
--#('CRCA', 'ProShares Ultra CRCL'),
--#('CRCG', 'Leverage Shares 2X Long CRCL Daily ETF'),
--#('CRK', 'Comstock Resources, Inc'),
--#('CRL', 'Charles River Laboratories'),
--#('CRM', 'Salesforce'),
--#('CRWD', 'CrowdStrike'),
--#('CSCO', 'Cisco'),
--#('CSGP', 'CoStar Group'),
--#('CSX', 'CSX Corporation'),
--#('CTAS', 'Cintas'),
--#('CTRA', 'Coterra'),
--#('CTSH', 'Cognizant'),
--#('CTVA', 'Corteva'),
--#('CURI', 'CuriosityStream'),
--#('CVS', 'CVS Health'),
--#('CVX', 'Chevron Corporation'),
--#('CZR', 'Caesars Entertainment'),
--#('D', 'Dominion Energy'),
--#('DAL', 'Delta Air Lines'),
--#('DAN', 'Dana Incorporated'),
--#('DAR', 'Darling Ingredients'),
--#('DASH', 'DoorDash'),
--#('DAY', 'Dayforce'),
--#('DD', 'DuPont'),
--#('DDOG', 'Datadog'),
--#('DE', 'Deere & Company'),
--#('DECK', 'Deckers Brands'),
--#('DELL', 'Dell Technologies'),
--#('DFDV', 'Data Farm REIT'),
--#('DG', 'Dollar General'),
--#('DGX', 'Quest Diagnostics'),
--#('DHI', 'D. R. Horton'),
--#('DHR', 'Danaher Corporation'),
--#('DIS', 'Walt Disney Company (The)'),
--#('DKNG', 'DraftKings'),
--#('DLR', 'Digital Realty'),
--#('DLTR', 'Dollar Tree'),
--#('DOC', 'Healthpeak Properties'),
--#('DOMO', 'Domo'),
--#('DOV', 'Dover Corporation'),
--#('DOW', 'Dow Inc.'),
--#('DRI', 'Darden Restaurants'),
--#('DRS', 'Leonardo DRS Inc'),
--#('DT', 'Dynatrace Inc'),
--#('DTE', 'DTE Energy'),
--#('DUK', 'Duke Energy'),
--#('DVA', 'DaVita'),
--#('DVN', 'Devon Energy'),
--#('DXCM', 'Dexcom'),
--#('DXYZ', 'Destiny Tech100 Inc'),
--#('EA', 'Electronic Arts'),
--#('EBAY', 'eBay'),
--#('ECL', 'Ecolab'),
--#('ED', 'Consolidated Edison'),
--#('EFX', 'Equifax'),
--#('EG', 'Everest Group'),
--#('EIX', 'Edison International'),
--#('EL', 'Estée Lauder Companies (The)'),
--#('ELV', 'Elevance Health'),
--#('EMN', 'Eastman Chemical Company'),
--#('EMR', 'Emerson Electric'),
--#('ENB', 'Enbridge'),
--#('ENPH', 'Enphase Energy'),
--#('EOG', 'EOG Resources'),
--#('EOSE', 'Eos Energy Enterprises'),
--#('EPAM', 'EPAM Systems'),
--#('EPD', 'Enterprise Products Partners'),
--#('EPSM', 'Epsium Enterprise Ltd'),
--#('EQH', 'Equitable Holdings Inc'),
--#('EQIX', 'Equinix'),
--#('EQR', 'Equity Residential'),
--#('EQT', 'EQT Corporation'),
--#('ERIE', 'Erie Indemnity'),
--#('ES', 'Eversource Energy'),
--#('ESS', 'Essex Property Trust'),
--#('ETH', 'Grayscale Ethereum Mini Trust ETF'),
--#('ETHA', 'iShares Ethereum Trust'),
--#('ETHD', 'Etho Climate Leadership U.S. ETF'),
--#('ETHE', 'Grayscale Ethereum Trust ETF'),
--#('ETHW', 'Bitwise Ethereum ETF Beneficial Interest'),
--#('ETN', 'Eaton Corporation'),
--#('ETR', 'Entergy'),
--#('EVLV', 'Evolv Technologies'),
--#('EVRG', 'Evergy'),
--#('EW', 'Edwards Lifesciences'),
--#('EXC', 'Exelon'),
--#('EXE', 'Expand Energy'),
--#('EXPD', 'Expeditors International'),
--#('EXPE', 'Expedia Group'),
--#('EXR', 'Extra Space Storage'),
--#('F', 'Ford Motor Company'),
--#('FANG', 'Diamondback Energy'),
--#('FAST', 'Fastenal'),
--#('FBL', 'GraniteShares 2x Long META Daily ETF'),
--#('FCEL', 'FuelCell Energy'),
--#('FCX', 'Freeport-McMoRan'),
--#('FDS', 'FactSet'),
--#('FDX', 'FedEx'),
--#('FE', 'FirstEnergy'),
--#('FETH', 'Fidelity Ethereum Fund Beneficial Interest'),
--#('FFIV', 'F5, Inc.'),
--#('FI', 'Fiserv'),
--#('FICO', 'Fair Isaac'),
--#('FIGR', 'Figure Technology Solutions Inc'),
--#('FIS', 'Fidelity National Information Services'),
--#('FITB', 'Fifth Third Bancorp'),
--#('FIVN', 'Five9'),
--#('FLO', 'Flowers Foods'),
--#('FLY', 'Firefly Aerospace Inc'),
--#('FMC', 'FMC Corp'),
--#('FMFC', 'Kandal M Venture Ltd'),
--#('FOFO', 'Hang Feng Technology Innovation Co Ltd'),
--#('FOX', 'Fox Corporation (Class B)'),
--#('FOXA', 'Fox Corporation (Class A)'),
--#('FRMI', 'Fermi Inc'),
--#('FROG', 'JFrog Ltd'),
--#('FRT', 'Federal Realty Investment Trust'),
--#('FSLR', 'First Solar'),
--#('FSTR', 'L.B. Foster'),
--#('FTEK', 'Fuel Tech'),
--#('FTI', 'TechnipFMC plc'),
--#('FTNT', 'Fortinet'),
--#('FTV', 'Fortive'),
--#('FUN', 'Six Flags Entertainment Corp'),
--#('FWRD', 'Forward Air Corp'),
--#('GBCI', 'Glacier Bancorp, Inc'),
--#('GCT', 'GigaCloud Technology Inc'),
--#('GD', 'General Dynamics'),
--#('GDDY', 'GoDaddy'),
--#('GE', 'GE Aerospace'),
--#('GEHC', 'GE HealthCare'),
--#('GEMI', 'Gemini Space Station Inc'),
--#('GEN', 'Gen Digital'),
--#('GEV', 'GE Vernova'),
--#('GILD', 'Gilead Sciences'),
--#('GIS', 'General Mills'),
--#('GL', 'Globe Life'),
--#('GLW', 'Corning Inc.'),
--#('GM', 'General Motors'),
--#('GNRC', 'Generac'),
--#('GOOG', 'Alphabet Inc. (Class C)'),
--#('GOOGL', 'Alphabet Inc. (Class A)'),
--#('GPC', 'Genuine Parts Company'),
--#('GPN', 'Global Payments'),
--#('GPRE', 'Green Plains'),
--#('GPRK', 'GeoPark'),
--#('GRMN', 'Garmin'),
--#('GRND', 'Grindr'),
--#('GRNT', 'Granite Ridge Resources'),
--#('GRPN', 'Groupon Inc'),
--#('GS', 'Goldman Sachs'),
--#('GTLB', 'Gitlab Inc'),
--#('GUSH', 'Direxion Daily S&P Oil & Gas Exp. & Prod. Bull 2X Shares'),
--#('GWAV', 'Greenwave Technology Solutions Inc'),
--#('GWW', 'W. W. Grainger'),
--#('HAL', 'Halliburton'),
--#('HAS', 'Hasbro'),
--#('HBAN', 'Huntington Bancshares'),
--#('HCA', 'HCA Healthcare'),
--#('HD', 'Home Depot (The)'),
--#('HDSN', 'Hudson Technologies'),
--#('HGV', 'Hilton Grand Vacations Inc'),
--#('HIG', 'Hartford (The)'),
--#('HII', 'Huntington Ingalls Industries'),
--#('HIMS', 'Hims & Hers Health'),
--#('HIMZ', 'Defiance Daily Target 2X Long HIMS ETF'),
--#('HLT', 'Hilton Worldwide'),
--#('HNGE', 'Hinge Health Inc'),
--#('HNI', 'HNI Corp'),
--#('HOLX', 'Hologic'),
--#('HON', 'Honeywell'),
--#('HPE', 'Hewlett Packard Enterprise'),
--#('HPQ', 'HP Inc.'),
--#('HRL', 'Hormel Foods'),
--#('HROW', 'Harrow Inc'),
--#('HSDT', 'Solana Co'),
--#('HSIC', 'Henry Schein'),
--#('HST', 'Host Hotels & Resorts'),
--#('HSY', 'Hershey Company (The)'),
--#('HTZ', 'Hertz Global Holdings'),
--#('HUBB', 'Hubbell Incorporated'),
--#('HUM', 'Humana'),
--#('HUSA', 'Houston American Energy'),
--#('HUT', 'Hut 8 Mining'),
--#('HWM', 'Howmet Aerospace'),
--#('HYPD', 'Hyperion DeFi Inc'),
--#('IBM', 'IBM'),
--#('ICE', 'Intercontinental Exchange'),
--#('IDA', 'IDACORP'),
--#('IDXX', 'Idexx Laboratories'),
--#('IEX', 'IDEX Corporation'),
--#('IFF', 'International Flavors & Fragrances'),
--#('INCY', 'Incyte'),
--#('INTA', 'Intapp Inc'),
--#('INTC', 'Intel'),
--#('INTU', 'Intuit'),
--#('INVH', 'Invitation Homes'),
--#('IOT', 'Samsara Inc'),
--#('IP', 'International Paper'),
--#('IPG', 'Interpublic Group of Companies (The)'),
--#('IQV', 'IQVIA'),
--#('IR', 'Ingersoll Rand'),
--#('IREN', 'Iris Energy'),
--#('IRM', 'Iron Mountain'),
--#('ISRG', 'Intuitive Surgical'),
--#('IT', 'Gartner'),
--#('ITW', 'Illinois Tool Works'),
--#('IVZ', 'Invesco'),
--#('J', 'Jacobs Solutions'),
--#('JACK', 'Jack In The Box, Inc'),
--#('JBHT', 'J.B. Hunt'),
--#('JBI', 'Janus International'),
--#('JBL', 'Jabil'),
--#('JCI', 'Johnson Controls'),
--#('JKHY', 'Jack Henry & Associates'),
--#('JNJ', 'Johnson & Johnson'),
--#('JOBY', 'Joby Aviation'),
--#('JPM', 'JPMorgan Chase'),
--#('K', 'Kellanova'),
--#('KALA', 'Kala Bio Inc'),
--#('KBR', 'KBR Inc'),
--#('KDP', 'Keurig Dr Pepper'),
--#('KEY', 'KeyCorp'),
--#('KEYS', 'Keysight Technologies'),
--#('KHC', 'Kraft Heinz'),
--#('KIM', 'Kimco Realty'),
--#('KKR', 'KKR'),
--#('KLAC', 'KLA Corporation'),
--#('KLIC', 'Kulicke & Soffa Industries, Inc'),
--#('KMB', 'Kimberly-Clark'),
--#('KMI', 'Kinder Morgan'),
--#('KMPR', 'Kemper Corporation'),
--#('KMX', 'CarMax'),
--#('KNTK', 'Kinetik Holdings Inc'),
--#('KO', 'Coca-Cola Company (The)'),
--#('KODK', 'Eastman Kodak'),
--#('KOPN', 'Kopin Corporation'),
--#('KR', 'Kroger'),
--#('KTOS', 'Kratos Defense'),
--#('KVUE', 'Kenvue'),
--#('KVYO', 'Klaviyo Inc'),
--#('L', 'Loews Corporation'),
--#('LABD', 'Direxion Daily S&P Biotech Bear 3X Shares'),
--#('LAZ', 'Lazard Inc'),
--#('LCID', 'Lucid Group Inc'),
--#('LDOS', 'Leidos'),
--#('LEGN', 'Legend Biotech Corp ADR'),
--#('LEN', 'Lennar'),
--#('LENZ', 'LENZ Therapeutics Inc'),
--#('LH', 'LabCorp'),
--#('LHX', 'L3Harris'),
--#('LII', 'Lennox International'),
--#('LIN', 'Linde plc'),
--#('LINE', 'Lineage Inc'),
--#('LKQ', 'LKQ Corporation'),
--#('LLY', 'Lilly (Eli)'),
--#('LMND', 'Lemonade Inc'),
--#('LMT', 'Lockheed Martin'),
--#('LNC', 'Lincoln National Corp'),
--#('LNT', 'Alliant Energy'),
--#('LQDA', 'Liquidia Corp'),
--#('LRCX', 'Lam Research'),
--#('LTBR', 'Lightbridge Corporation'),
--#('LULU', 'Lululemon Athletica'),
--#('LUV', 'Southwest Airlines'),
--#('LVS', 'Las Vegas Sands'),
--#('LW', 'Lamb Weston'),
--#('LYB', 'LyondellBasell'),
--#('LYFT', 'Lyft'),
--#('LYV', 'Live Nation Entertainment'),
--#('MA', 'Mastercard'),
--#('MAA', 'Mid-America Apartment Communities'),
--#('MAN', 'ManpowerGroup'),
--#('MAPS', 'WM Technology'),
--#('MAR', 'Marriott International'),
--#('MARA', 'Marathon Digital Holdings'),
--#('MAS', 'Masco'),
--#('MBX', 'MBX Biosciences Inc'),
--#('MCHP', 'Microchip Technology'),
--#('MCK', 'McKesson Corporation'),
--#('MDLZ', 'Mondelez International'),
--#('MDT', 'Medtronic'),
--#('MET', 'MetLife'),
--#('META', 'Meta Platforms'),
--#('METC', 'Ramaco Resources'),
--#('METU', 'Direxion Daily META Bull 2X Shares'),
--#('MGM', 'MGM Resorts'),
--#('MGNI', 'Magnite'),
--#('MHK', 'Mohawk Industries'),
--#('MKC', 'McCormick & Company'),
--#('MKTX', 'MarketAxess'),
--#('MLM', 'Martin Marietta Materials'),
--#('MMC', 'Marsh McLennan'),
--#('MMM', '3M'),
--#('MNST', 'Monster Beverage'),
--#('MO', 'Altria'),
--#('MOH', 'Molina Healthcare'),
--#('MOS', 'Mosaic Company (The)'),
--#('MPC', 'Marathon Petroleum'),
--#('MPWR', 'Monolithic Power Systems'),
--#('MQ', 'Marqeta'),
--#('MRK', 'Merck & Co.'),
--#('MRNA', 'Moderna'),
--#('MS', 'Morgan Stanley'),
--#('MSCI', 'MSCI'),
--#('MSFT', 'Microsoft'),
--#('MSI', 'Motorola Solutions'),
--#('MSOX', 'AdvisorShares MSOS 2x Daily ETF'),
--#('MSTX', 'Defiance Daily Target 2x Long MSTR ETF'),
--#('MTB', 'M&T Bank'),
--#('MTCH', 'Match Group'),
--#('MTD', 'Mettler Toledo'),
--#('MTDR', 'Matador Resources Co'),
--#('MU', 'Micron Technology'),
--#('NATL', 'NCR Atleos Corp'),
--#('NCLH', 'Norwegian Cruise Line Holdings'),
--#('NDAQ', 'Nasdaq, Inc.'),
--#('NDSN', 'Nordson Corporation'),
--#('NE', 'Noble Corp Plc'),
--#('NEE', 'NextEra Energy'),
--#('NEGG', 'Newegg Commerce Inc'),
--#('NEM', 'Newmont'),
--#('NEXT', 'NextDecade'),
--#('NFLX', 'Netflix'),
--#('NG', 'NovaGold Resources'),
--#('NI', 'NiSource'),
--#('NKE', 'Nike, Inc.'),
--#('NN', 'NextNav'),
--#('NOC', 'Northrop Grumman'),
--#('NOG', 'Northern Oil and Gas Inc'),
--#('NOW', 'ServiceNow'),
--#('NP', 'Neptune Insurance Holdings Inc'),
--#('NPKI', 'Neuropace'),
--#('NRG', 'NRG Energy'),
--#('NSC', 'Norfolk Southern Railway'),
--#('NSP', 'Insperity Inc'),
--#('NTAP', 'NetApp'),
--#('NTRS', 'Northern Trust'),
--#('NTSK', 'Netskope Inc'),
--#('NUE', 'Nucor'),
--#('NVDA', 'Nvidia'),
--#('NVDD', 'Direxion Daily NVDA Bear 1X Shares'),
--#('NVR', 'NVR, Inc.'),
--#('NWS', 'News Corp (Class B)'),
--#('NWSA', 'News Corp (Class A)'),
--#('NXPI', 'NXP Semiconductors'),
--#('NXT', 'Nextracker'),
--#('O', 'Realty Income'),
--#('ODFL', 'Old Dominion'),
--#('OKE', 'ONEOK'),
--#('OLN', 'Olin Corp'),
--#('OM', 'Outset Medical'),
--#('OMC', 'Omnicom Group'),
--#('ON', 'ON Semiconductor'),
--#('ORBS', 'Eightco Holdings Inc'),
--#('ORCL', 'Oracle Corporation'),
--#('OTIS', 'Otis Worldwide'),
--#('OUST', 'Ouster Inc'),
--#('OVV', 'Ovintiv Inc'),
--#('OXY', 'Occidental Petroleum'),
--#('OZK', 'Bank OZK'),
--#('PANW', 'Palo Alto Networks'),
--#('PAR', 'Par Technology Corp'),
--#('PARA', 'Paramount Global'),
--#('PAY', 'Paymentus Holdings Inc'),
--#('PAYC', 'Paycom'),
--#('PAYX', 'Paychex'),
--#('PBYI', 'Puma Biotechnology'),
--#('PCAR', 'Paccar'),
--#('PCG', 'PG&E Corporation'),
--#('PCT', 'PureCycle Technologies'),
--#('PDYN', 'Palladyne AI'),
--#('PEG', 'Public Service Enterprise Group'),
--#('PENG', 'Penguin Solutions Inc'),
--#('PEP', 'PepsiCo'),
--#('PFE', 'Pfizer'),
--#('PFG', 'Principal Financial Group'),
--#('PG', 'Procter & Gamble'),
--#('PGEN', 'Precigen'),
--#('PGNY', 'Progyny Inc'),
--#('PGR', 'Progressive Corporation'),
--#('PGY', 'Pagaya Technologies Ltd'),
--#('PH', 'Parker Hannifin'),
--#('PHM', 'PulteGroup'),
--#('PHR', 'Phreesia Inc'),
--#('PINC', 'Premier Inc.'),
--#('PINS', 'Pinterest Inc'),
--#('PKG', 'Packaging Corporation of America'),
--#('PLD', 'Prologis'),
--#('PLTR', 'Palantir Technologies'),
--#('PM', 'Philip Morris International'),
--#('PNC', 'PNC Financial Services'),
--#('PNR', 'Pentair'),
--#('PNW', 'Pinnacle West'),
--#('PODD', 'Insulet Corporation'),
--#('PONY', 'Pony AI'),
--#('POOL', 'Pool Corporation'),
--#('PPC', 'Pilgrim''s Pride Corp'),
--#('PPG', 'PPG Industries'),
--#('PPL', 'PPL Corporation'),
--#('PPTA', 'Perpetua Resources'),
--#('PRCH', 'Porch Group'),
--#('PRCT', 'Procept BioRobotics Corp'),
--#('PRU', 'Prudential Financial'),
--#('PSA', 'Public Storage'),
--#('PSX', 'Phillips 66'),
--#('PTC', 'PTC Inc.'),
--#('PWR', 'Quanta Services'),
--#('PXED', 'Phoenix Education Partners Inc'),
--#('PYPL', 'PayPal'),
--#('QBTS', 'D-Wave Quantum'),
--#('QBTZ', 'Defiance Daily Target 2x Short QBTS ETF'),
--#('QCOM', 'Qualcomm'),
--#('QS', 'QuantumScape'),
--#('QUBT', 'Quantum Computing'),
--#('QUBX', 'Tradr 2X Long QUBT Daily ETF'),
--#('RAL', 'Ralliant Corp'),
--#('RBLX', 'Roblox'),
--#('RCL', 'Royal Caribbean Group'),
--#('RDTL', 'GraniteShares 2x Long RDDT Daily ETF'),
--#('REG', 'Regency Centers'),
--#('REGN', 'Regeneron Pharmaceuticals'),
--#('RF', 'Regions Financial Corporation'),
--#('RGTI', 'Rigetti Computing'),
--#('RGTZ', 'Defiance Daily Target 2x Short RGTI ETF'),
--#('RHI', 'Robert Half Inc'),
--#('RIGL', 'Rigel Pharmaceuticals'),
--#('RJF', 'Raymond James Financial'),
--#('RL', 'Ralph Lauren Corporation'),
--#('RMBS', 'Rambus'),
--#('RMD', 'ResMed'),
--#('RNG', 'RingCentral Inc'),
--#('RNST', 'Renasant Corp'),
--#('ROK', 'Rockwell Automation'),
--#('ROL', 'Rollins, Inc.'),
--#('ROP', 'Roper Technologies'),
--#('ROST', 'Ross Stores'),
--#('RSG', 'Republic Services'),
--#('RSI', 'Rush Street Interactive Inc'),
--#('RTX', 'RTX Corporation'),
--#('RUN', 'Sunrun'),
--#('RVTY', 'Revvity'),
--#('RXST', 'RxSight'),
--#('SATL', 'Satellogic'),
--#('SATS', 'EchoStar'),
--#('SBAC', 'SBA Communications'),
--#('SBET', 'SharpLink Gaming Inc'),
--#('SBUX', 'Starbucks'),
--#('SCHW', 'Charles Schwab Corporation'),
--#('SDGR', 'Schrodinger Inc'),
--#('SDOW', 'ProShares UltraPro Short Dow30 -3x Shares'),
--#('SERV', 'Serve Robotics'),
--#('SEV', 'Aptera Motors Corp'),
--#('SGBX', 'Safe & Green Holdings Corp'),
--#('SHAK', 'Shake Shack'),
--#('SHLS', 'Shoals Technologies'),
--#('SHW', 'Sherwin-Williams'),
--#('SJM', 'J.M. Smucker Company (The)'),
--#('SLB', 'Schlumberger'),
--#('SLDB', 'Solid Biosciences'),
--#('SM', 'SM Energy Co'),
--#('SMCI', 'Supermicro'),
--#('SMCL', 'Smurfit Kappa'),
--#('SMLR', 'Semler Scientific Inc'),
--#('SMMT', 'Summit Therapeutics Inc'),
--#('SMST', 'Safehold'),
--#('SNA', 'Snap-on'),
--#('SNDL', 'SNDL Inc.'),
--#('SNPS', 'Synopsys'),
--#('SNV', 'Synovus Financial Corp'),
--#('SO', 'Southern Company'),
--#('SOC', 'Sable Offshore'),
--#('SOFI', 'SoFi Technologies'),
--#('SOFX', 'Defiance Daily Target 2X Long SOFI ETF'),
--#('SOLT', '2x Solana ETF'),
--#('SOLV', 'Solventum'),
--#('SOLZ', 'Solana ETF'),
--#('SPG', 'Simon Property Group'),
--#('SPGI', 'S&P Global'),
--#('SPXS', 'Direxion Daily S&P 500 Bear -3X Shares'),
--#('SRE', 'Sempra'),
--#('SRFM', 'Surf Air Mobility'),
--#('SRRK', 'Scholar Rock Holding Corp'),
--#('SSK', 'REX-Osprey SOL + Staking ETF'),
--#('SSRM', 'SSR Mining'),
--#('ST', 'Sensata Technologies Holding Plc'),
--#('STE', 'Steris'),
--#('STEM', 'Stem Inc.'),
--#('STLD', 'Steel Dynamics'),
--#('STNE', 'StoneCo'),
--#('STT', 'State Street Corporation'),
--#('STUB', 'Stubhub Holdings Inc'),
--#('STX', 'Seagate Technology'),
--#('STZ', 'Constellation Brands'),
--#('SVIX', '1x Short VIX Futures ETF'),
--#('SVXY', 'ProShares Short VIX Short-Term Futures ETF -1x Shares'),
--#('SW', 'Smurfit WestRock'),
--#('SWK', 'Stanley Black & Decker'),
--#('SWKS', 'Skyworks Solutions'),
--#('SYF', 'Synchrony Financial'),
--#('SYK', 'Stryker Corporation'),
--#('SYY', 'Sysco'),
--#('T', 'AT&T'),
--#('TAP', 'Molson Coors Beverage Company'),
--#('TDG', 'TransDigm Group'),
--#('TDS', 'Telephone And Data Systems, Inc'),
--#('TDW', 'Tidewater Inc'),
--#('TDY', 'Teledyne Technologies'),
--#('TECH', 'Bio-Techne'),
--#('TECS', 'Direxion Daily Technology Bear -3X Shares'),
--#('TEL', 'TE Connectivity'),
--#('TER', 'Teradyne'),
--#('TETH', '21Shares Ethereum ETF'),
--#('TFC', 'Truist Financial'),
--#('TGT', 'Target Corporation'),
--#('TJX', 'TJX Companies'),
--#('TKO', 'TKO Group Holdings'),
--#('TMO', 'Thermo Fisher Scientific'),
--#('TMUS', 'T-Mobile US'),
--#('TNXP', 'Tonix Pharmaceuticals Holding Corp'),
--#('TOST', 'Toast Inc'),
--#('TPL', 'Texas Pacific Land Corporation'),
--#('TPR', 'Tapestry, Inc.'),
--#('TRGP', 'Targa Resources'),
--#('TRMB', 'Trimble Inc.'),
--#('TROW', 'T. Rowe Price'),
--#('TRP', 'TC Energy'),
--#('TRV', 'Travelers Companies (The)'),
--#('TSCO', 'Tractor Supply'),
--#('TSDD', 'GraniteShares 2x Short TSLA Daily ETF'),
--#('TSLA', 'Tesla, Inc.'),
--#('TSLL', 'Direxion Daily TSLA Bull 2X Shares'),
--#('TSN', 'Tyson Foods'),
--#('TSSI', 'TSS Inc.'),
--#('TT', 'Trane Technologies'),
--#('TTC', 'Toro Company'),
--#('TTD', 'The Trade Desk'),
--#('TTRX', 'Turn Therapeutics Inc'),
--#('TTWO', 'Take-Two Interactive'),
--#('TXN', 'Texas Instruments'),
--#('TXT', 'Textron'),
--#('TYL', 'Tyler Technologies'),
--#('U', 'Unity Software Inc'),
--#('UAL', 'United Airlines Holdings'),
--#('UBER', 'Uber'),
--#('UDR', 'UDR, Inc.'),
--#('UEC', 'Uranium Energy Corp'),
--#('UFPI', 'UFP Industries'),
--#('UHS', 'Universal Health Services'),
--#('ULTA', 'Ulta Beauty'),
--#('UMAC', 'Unusual Machines'),
--#('UNH', 'UnitedHealth Group'),
--#('UNP', 'Union Pacific Corporation'),
--#('UPS', 'United Parcel Service'),
--#('UPST', 'Upstart Holdings Inc'),
--#('UPSX', 'Tradr 2X Long UPST Daily ETF'),
--#('URBN', 'Urban Outfitters'),
--#('URI', 'United Rentals'),
--#('USAR', 'USA Rare Earth'),
--#('USB', 'U.S. Bancorp'),
--#('UUUU', 'Energy Fuels'),
--#('V', 'Visa Inc.'),
--#('VG', 'Vonage Holdings'),
--#('VIA', 'Via Transportation Inc'),
--#('VICI', 'Vici Properties'),
--#('VITL', 'Vital Farms Inc'),
--#('VLO', 'Valero Energy'),
--#('VLTO', 'Veralto'),
--#('VMC', 'Vulcan Materials Company'),
--#('VNO', 'Vornado Realty Trust'),
--#('VNOM', 'Viper Energy Inc'),
--#('VRSK', 'Verisk Analytics'),
--#('VRSN', 'Verisign'),
--#('VRTX', 'Vertex Pharmaceuticals'),
--#('VSAT', 'Viasat'),
--#('VST', 'Vistra Corp.'),
--#('VTLE', 'Vital Energy'),
--#('VTR', 'Ventas'),
--#('VTRS', 'Viatris'),
--#('VZ', 'Verizon'),
--#('WAB', 'Wabtec'),
--#('WAT', 'Waters Corporation'),
--#('WAY', 'Waystar Holding Corp'),
--#('WBA', 'Walgreens Boots Alliance'),
--#('WBD', 'Warner Bros. Discovery'),
--#('WBI', 'WaterBridge Infrastructure LLC'),
--#('WDAY', 'Workday, Inc.'),
--#('WDC', 'Western Digital'),
--#('WEC', 'WEC Energy Group'),
--#('WELL', 'Welltower'),
--#('WFC', 'Wells Fargo'),
--#('WGO', 'Winnebago Industries, Inc'),
--#('WHD', 'Cactus Inc'),
--#('WM', 'Waste Management'),
--#('WMB', 'Williams Companies'),
--#('WMT', 'Walmart'),
--#('WOLF', 'Wolfspeed Inc'),
--#('WRB', 'W. R. Berkley Corporation'),
--#('WSM', 'Williams-Sonoma'),
--#('WST', 'West Pharmaceutical Services'),
--#('WTW', 'Willis Towers Watson'),
--#('WY', 'Weyerhaeuser'),
--#('WYNN', 'Wynn Resorts'),
--#('XEL', 'Xcel Energy'),
--#('XMTR', 'Xometry Inc'),
--#('XOM', 'ExxonMobil'),
--#('XRPT', 'Volatility Shares Trust XRP 2X ETF'),
--#('XXRP', 'Teucrium 2x Long Daily XRP ETF'),
--#('XYL', 'Xylem Inc.'),
--#('YANG', 'Direxion Daily FTSE China Bear -3X Shares'),
--#('YETI', 'YETI Holdings Inc'),
--#('YEXT', 'Yext'),
--#('YINN', 'Direxion Daily FTSE China Bull 3X Shares'),
--#('YOU', 'Clear Secure Inc'),
--#('YUM', 'Yum! Brands'),
--#('ZBH', 'Zimmer Biomet'),
--#('ZBRA', 'Zebra Technologies'),
--#('ZD', 'Ziff Davis Inc'),
--#('ZETA', 'Zeta Global Holdings Corp'),
--#('ZION', 'Zions Bancorporation N.A'),
('ZTS', 'Zoetis'); 

-- Total: 623 symbols (S&P 500 + Additional stocks)
>>>>>>> cc4b37108849f1e58ba1d5bb882acda0dbc0077f
