use StockPxLabs;
-- Drop tables if they exist (in correct order - child tables first, then parents)
DROP TABLE IF EXISTS user_trades;
DROP TABLE IF EXISTS user_preferences;
DROP TABLE IF EXISTS stock_performance_metrics;
DROP TABLE IF EXISTS daily_stock_data;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS stock_symbols;
DROP TABLE IF EXISTS roles;

-- Create roles table
CREATE TABLE IF NOT EXISTS roles (
    id INT AUTO_INCREMENT PRIMARY KEY,
    role_name VARCHAR(50) NOT NULL UNIQUE,
    display_name VARCHAR(100) NOT NULL,
    description TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_role_name (role_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Insert default roles (ignore if they already exist)
INSERT IGNORE INTO roles (role_name, display_name, description) VALUES
('free', 'Free Tier', 'Basic access with limited features'),
('pro', 'Pro', 'Full access to all trading analysis features'),
('enterprise', 'Enterprise', 'Advanced features with priority support'),
('admin', 'Admin', 'Full system administration access');

-- Create stock_symbols table (no dependencies)
CREATE TABLE IF NOT EXISTS stock_symbols (
    id INT AUTO_INCREMENT PRIMARY KEY,
    symbol VARCHAR(10) UNIQUE NOT NULL,
    company_name VARCHAR(255),
    INDEX idx_symbol (symbol)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Create users table (depends on roles)
CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role_id INT NOT NULL DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_login TIMESTAMP NULL,
    is_active BOOLEAN DEFAULT TRUE,
    email_verified BOOLEAN DEFAULT FALSE,
    verification_token VARCHAR(255) NULL,
    verification_token_expires TIMESTAMP NULL,
    FOREIGN KEY (role_id) REFERENCES roles(id),
    INDEX idx_email (email),
    INDEX idx_active (is_active),
    INDEX idx_role_id (role_id),
    INDEX idx_verification_token (verification_token)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Create user_preferences table (depends on users)
CREATE TABLE IF NOT EXISTS user_preferences (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    name VARCHAR(100) NOT NULL,
    default_days INT DEFAULT 365,
    default_atr_period INT DEFAULT 14,
    default_atr_multiplier DECIMAL(3,1) DEFAULT 2.0,
    default_ma_type VARCHAR(10) DEFAULT 'ema',
    default_initial_capital DECIMAL(15,2) DEFAULT 100000.00,
    mean_reversion_threshold DECIMAL(5,2) DEFAULT 10.0,
    position_sizing_percentage DECIMAL(5,2) DEFAULT 5.0,
    trades_columns JSON,
    favorite_stocks JSON DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    INDEX idx_user_id (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Create daily_stock_data table (depends on stock_symbols)
CREATE TABLE IF NOT EXISTS daily_stock_data (
    id INT AUTO_INCREMENT PRIMARY KEY,
    symbol_id INT NOT NULL,
    date DATE NOT NULL,
    open DECIMAL(10,2),
    high DECIMAL(10,2),
    low DECIMAL(10,2),
    close DECIMAL(10,2),
    volume BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (symbol_id) REFERENCES stock_symbols(id) ON DELETE CASCADE,
    UNIQUE KEY unique_symbol_date (symbol_id, date),
    INDEX idx_symbol_id (symbol_id),
    INDEX idx_date (date),
    INDEX idx_symbol_date (symbol_id, date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Create stock_performance_metrics table (depends on stock_symbols)
CREATE TABLE IF NOT EXISTS stock_performance_metrics (
    id INT AUTO_INCREMENT PRIMARY KEY,
    symbol_id INT NOT NULL,
    analysis_date DATE NOT NULL,
    total_return_pct DECIMAL(8,2),
    total_pnl DECIMAL(15,2),
    win_rate DECIMAL(5,2),
    total_trades INT,
    sharpe_ratio DECIMAL(8,2),
    analysis_params JSON,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (symbol_id) REFERENCES stock_symbols(id) ON DELETE CASCADE,
    UNIQUE KEY unique_symbol_analysis_date (symbol_id, analysis_date),
    INDEX idx_symbol_analysis_date (symbol_id, analysis_date),
    INDEX idx_analysis_date (analysis_date),
    INDEX idx_total_return (total_return_pct),
    INDEX idx_sharpe_ratio (sharpe_ratio)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Create user_trades table (depends on users)
CREATE TABLE IF NOT EXISTS user_trades (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    symbol VARCHAR(10) NOT NULL,
    entry_date DATE NOT NULL,
    entry_price DECIMAL(10,2) NOT NULL,
    shares INT NOT NULL,
    exit_date DATE NULL,
    exit_price DECIMAL(10,2) NULL,
    stop_loss DECIMAL(10,2) NULL,
    target_price DECIMAL(10,2) NULL,
    trade_notes TEXT NULL,
    status ENUM('open', 'closed') DEFAULT 'open',
    pnl DECIMAL(15,2) NULL,
    pnl_percent DECIMAL(8,2) NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    INDEX idx_user_id (user_id),
    INDEX idx_symbol (symbol),
    INDEX idx_status (status),
    INDEX idx_entry_date (entry_date),
    INDEX idx_user_symbol (user_id, symbol)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Insert stock symbols (S&P 500 + Additional stocks)
INSERT IGNORE INTO stock_symbols (symbol, company_name) VALUES
('A', 'Agilent Technologies'),
('AA', 'Alcoa Corporation'),
('AAPL', 'Apple Inc.'),
('ABBV', 'AbbVie'),
('ABNB', 'Airbnb'),
('ABT', 'Abbott Laboratories'),
('ACGL', 'Arch Capital Group'),
('ACHR', 'Archer Aviation'),
('ACLS', 'Axcelis Technologies'),
('ACN', 'Accenture'),
('ADBE', 'Adobe Inc.'),
('ADI', 'Analog Devices'),
('ADM', 'Archer Daniels Midland'),
('ADP', 'Automatic Data Processing'),
('ADPT', 'Adaptive Biotechnologies'),
('ADSK', 'Autodesk'),
('ADT', 'ADT Inc.'),
('AEE', 'Ameren'),
('AEHR', 'Aehr Test Systems'),
('AEP', 'American Electric Power'),
('AES', 'AES Corporation'),
('AFL', 'Aflac'),
('AIG', 'American International Group'),
('AIZ', 'Assurant'),
('AJG', 'Arthur J. Gallagher & Co.'),
('AKAM', 'Akamai Technologies'),
('ALB', 'Albemarle Corporation'),
('ALGM', 'Allegro MicroSystems'),
('ALGN', 'Align Technology'),
('ALGT', 'Allegiant Travel'),
('ALK', 'Alaska Air Group'),
('ALL', 'Allstate'),
('ALLE', 'Allegion'),
('ALLY', 'Ally Financial'),
('AMAT', 'Applied Materials'),
('AMCR', 'Amcor'),
('AMD', 'Advanced Micro Devices'),
('AME', 'Ametek'),
('AMGN', 'Amgen'),
('AMP', 'Ameriprise Financial'),
('AMPX', 'Amprius Technologies'),
('AMRC', 'Ameresco'),
('AMT', 'American Tower'),
('AMZN', 'Amazon'),
('ANET', 'Arista Networks'),
('AON', 'Aon'),
('AOS', 'A. O. Smith'),
('APA', 'APA Corporation'),
('APD', 'Air Products'),
('APH', 'Amphenol'),
('APLD', 'Applied Digital'),
('APO', 'Apollo Global Management'),
('APPN', 'Appian'),
('APTV', 'Aptiv'),
('AR', 'Antero Resources'),
('ARE', 'Alexandria Real Estate Equities'),
('ARKX', 'ARK Space Exploration ETF'),
('ARMN', 'Aetherium Acquisition'),
('ASGN', 'ASGN Incorporated'),
('ASH', 'Ashland Global'),
('ASPI', 'ASP Isotopes'),
('ATMU', 'Atmus Filtration Technologies'),
('ATO', 'Atmos Energy'),
('AVB', 'AvalonBay Communities'),
('AVGO', 'Broadcom'),
('AVY', 'Avery Dennison'),
('AWK', 'American Water Works'),
('AXON', 'Axon Enterprise'),
('AXP', 'American Express'),
('AZO', 'AutoZone'),
('BA', 'Boeing'),
('BAC', 'Bank of America'),
('BALL', 'Ball Corporation'),
('BAX', 'Baxter International'),
('BBIO', 'BridgeBio Pharma'),
('BBY', 'Best Buy'),
('BBWI', 'Bath & Body Works'),
('BDX', 'Becton Dickinson'),
('BEN', 'Franklin Resources'),
('BF-B', 'Brown–Forman'),
('BG', 'Bunge Global'),
('BHF', 'Brighthouse Financial'),
('BIIB', 'Biogen'),
('BK', 'BNY Mellon'),
('BKKT', 'Bakkt Holdings'),
('BKNG', 'Booking Holdings'),
('BKR', 'Baker Hughes'),
('BKSY', 'BlackSky Technology'),
('BL', 'BlackLine'),
('BLDR', 'Builders FirstSource'),
('BLKB', 'Blackbaud'),
('BLK', 'BlackRock'),
('BMY', 'Bristol Myers Squibb'),
('BR', 'Broadridge Financial Solutions'),
('BRBR', 'BellRing Brands'),
('BRK-B', 'Berkshire Hathaway'),
('BRO', 'Brown & Brown'),
('BSX', 'Boston Scientific'),
('BTM', 'Bitcoin Depot'),
('BWIN', 'Baldwin Insurance Group'),
('BX', 'Blackstone Inc.'),
('BXP', 'BXP, Inc.'),
('C', 'Citigroup'),
('CAG', 'Conagra Brands'),
('CAH', 'Cardinal Health'),
('CARG', 'CarGurus'),
('CARR', 'Carrier Global'),
('CART', 'Maplebear (Instacart)'),
('CAT', 'Caterpillar Inc.'),
('CB', 'Chubb Limited'),
('CBOE', 'Cboe Global Markets'),
('CBRE', 'CBRE Group'),
('CBRL', 'Cracker Barrel'),
('CCI', 'Crown Castle'),
('CCL', 'Carnival'),
('CDNS', 'Cadence Design Systems'),
('CDW', 'CDW'),
('CE', 'Celanese'),
('CEG', 'Constellation Energy'),
('CF', 'CF Industries'),
('CFG', 'Citizens Financial Group'),
('CGNX', 'Cognex'),
('CHD', 'Church & Dwight'),
('CHRW', 'C.H. Robinson'),
('CHTR', 'Charter Communications'),
('CHYM', 'Chimerix'),
('CI', 'Cigna'),
('CINF', 'Cincinnati Financial'),
('CIVI', 'Civitas Resources'),
('CL', 'Colgate-Palmolive'),
('CLX', 'Clorox'),
('CMCSA', 'Comcast'),
('CME', 'CME Group'),
('CMG', 'Chipotle Mexican Grill'),
('CMI', 'Cummins'),
('CMS', 'CMS Energy'),
('CNC', 'Centene Corporation'),
('CNM', 'Core & Main'),
('CNP', 'CenterPoint Energy'),
('CNXC', 'Concentrix'),
('COF', 'Capital One'),
('COIN', 'Coinbase Global'),
('COO', 'Cooper Companies (The)'),
('COP', 'ConocoPhillips'),
('COR', 'Cencora'),
('CORZ', 'Core Scientific'),
('COST', 'Costco'),
('CPAY', 'Corpay'),
('CPB', 'Campbell Soup Company'),
('CPRT', 'Copart'),
('CPS', 'Cooper-Standard Holdings'),
('CPT', 'Camden Property Trust'),
('CRC', 'California Resources'),
('CRL', 'Charles River Laboratories'),
('CRM', 'Salesforce'),
('CRWD', 'CrowdStrike'),
('CSCO', 'Cisco'),
('CSGP', 'CoStar Group'),
('CSX', 'CSX Corporation'),
('CTAS', 'Cintas'),
('CTRA', 'Coterra'),
('CTSH', 'Cognizant'),
('CTVA', 'Corteva'),
('CURI', 'CuriosityStream'),
('CVS', 'CVS Health'),
('CVX', 'Chevron Corporation'),
('CZR', 'Caesars Entertainment'),
('D', 'Dominion Energy'),
('DAL', 'Delta Air Lines'),
('DAN', 'Dana Incorporated'),
('DAR', 'Darling Ingredients'),
('DASH', 'DoorDash'),
('DAY', 'Dayforce'),
('DD', 'DuPont'),
('DDOG', 'Datadog'),
('DE', 'Deere & Company'),
('DECK', 'Deckers Brands'),
('DELL', 'Dell Technologies'),
('DFDV', 'Data Farm REIT'),
('DG', 'Dollar General'),
('DGX', 'Quest Diagnostics'),
('DHI', 'D. R. Horton'),
('DHR', 'Danaher Corporation'),
('DIS', 'Walt Disney Company (The)'),
('DKNG', 'DraftKings'),
('DLR', 'Digital Realty'),
('DLTR', 'Dollar Tree'),
('DOC', 'Healthpeak Properties'),
('DOMO', 'Domo'),
('DOV', 'Dover Corporation'),
('DOW', 'Dow Inc.'),
('DPZ', 'Domino''s'),
('DRI', 'Darden Restaurants'),
('DTE', 'DTE Energy'),
('DUK', 'Duke Energy'),
('DVA', 'DaVita'),
('DVN', 'Devon Energy'),
('DXCM', 'Dexcom'),
('EA', 'Electronic Arts'),
('EBAY', 'eBay'),
('ECL', 'Ecolab'),
('ED', 'Consolidated Edison'),
('EFX', 'Equifax'),
('EG', 'Everest Group'),
('EIX', 'Edison International'),
('EL', 'Estée Lauder Companies (The)'),
('ELV', 'Elevance Health'),
('EMN', 'Eastman Chemical Company'),
('EMR', 'Emerson Electric'),
('ENB', 'Enbridge'),
('ENPH', 'Enphase Energy'),
('EOG', 'EOG Resources'),
('EOSE', 'Eos Energy Enterprises'),
('EPAM', 'EPAM Systems'),
('EPD', 'Enterprise Products Partners'),
('EQIX', 'Equinix'),
('EQR', 'Equity Residential'),
('EQT', 'EQT Corporation'),
('ERIE', 'Erie Indemnity'),
('ES', 'Eversource Energy'),
('ESS', 'Essex Property Trust'),
('ETHD', 'Etho Climate Leadership U.S. ETF'),
('ETN', 'Eaton Corporation'),
('ETR', 'Entergy'),
('EVRG', 'Evergy'),
('EVLV', 'Evolv Technologies'),
('EW', 'Edwards Lifesciences'),
('EXC', 'Exelon'),
('EXE', 'Expand Energy'),
('EXPD', 'Expeditors International'),
('EXPE', 'Expedia Group'),
('EXR', 'Extra Space Storage'),
('F', 'Ford Motor Company'),
('FANG', 'Diamondback Energy'),
('FAST', 'Fastenal'),
('FCX', 'Freeport-McMoRan'),
('FCEL', 'FuelCell Energy'),
('FDS', 'FactSet'),
('FDX', 'FedEx'),
('FE', 'FirstEnergy'),
('FFIV', 'F5, Inc.'),
('FI', 'Fiserv'),
('FICO', 'Fair Isaac'),
('FIS', 'Fidelity National Information Services'),
('FITB', 'Fifth Third Bancorp'),
('FIVN', 'Five9'),
('FLO', 'Flowers Foods'),
('FOX', 'Fox Corporation (Class B)'),
('FOXA', 'Fox Corporation (Class A)'),
('FRT', 'Federal Realty Investment Trust'),
('FSLR', 'First Solar'),
('FSTR', 'L.B. Foster'),
('FTEK', 'Fuel Tech'),
('FTNT', 'Fortinet'),
('FTV', 'Fortive'),
('GD', 'General Dynamics'),
('GDDY', 'GoDaddy'),
('GE', 'GE Aerospace'),
('GEHC', 'GE HealthCare'),
('GEN', 'Gen Digital'),
('GEV', 'GE Vernova'),
('GILD', 'Gilead Sciences'),
('GIS', 'General Mills'),
('GL', 'Globe Life'),
('GLW', 'Corning Inc.'),
('GM', 'General Motors'),
('GNRC', 'Generac'),
('GOOG', 'Alphabet Inc. (Class C)'),
('GOOGL', 'Alphabet Inc. (Class A)'),
('GPC', 'Genuine Parts Company'),
('GPN', 'Global Payments'),
('GPRE', 'Green Plains'),
('GPRK', 'GeoPark'),
('GRMN', 'Garmin'),
('GRND', 'Grindr'),
('GRNT', 'Granite Ridge Resources'),
('GS', 'Goldman Sachs'),
('GWW', 'W. W. Grainger'),
('HAL', 'Halliburton'),
('HAS', 'Hasbro'),
('HBAN', 'Huntington Bancshares'),
('HCA', 'HCA Healthcare'),
('HD', 'Home Depot (The)'),
('HDSN', 'Hudson Technologies'),
('HES', 'Hess Corporation'),
('HIG', 'Hartford (The)'),
('HII', 'Huntington Ingalls Industries'),
('HIMS', 'Hims & Hers Health'),
('HLT', 'Hilton Worldwide'),
('HOLX', 'Hologic'),
('HON', 'Honeywell'),
('HPE', 'Hewlett Packard Enterprise'),
('HPQ', 'HP Inc.'),
('HRL', 'Hormel Foods'),
('HSIC', 'Henry Schein'),
('HST', 'Host Hotels & Resorts'),
('HSY', 'Hershey Company (The)'),
('HTZ', 'Hertz Global Holdings'),
('HUBB', 'Hubbell Incorporated'),
('HUM', 'Humana'),
('HUSA', 'Houston American Energy'),
('HUT', 'Hut 8 Mining'),
('HWM', 'Howmet Aerospace'),
('IBM', 'IBM'),
('ICE', 'Intercontinental Exchange'),
('IDA', 'IDACORP'),
('IDXX', 'Idexx Laboratories'),
('IEX', 'IDEX Corporation'),
('IFF', 'International Flavors & Fragrances'),
('INCY', 'Incyte'),
('INTC', 'Intel'),
('INTU', 'Intuit'),
('INVH', 'Invitation Homes'),
('IREN', 'Iris Energy'),
('IP', 'International Paper'),
('IPG', 'Interpublic Group of Companies (The)'),
('IQV', 'IQVIA'),
('IR', 'Ingersoll Rand'),
('IRM', 'Iron Mountain'),
('ISRG', 'Intuitive Surgical'),
('IT', 'Gartner'),
('ITW', 'Illinois Tool Works'),
('IVZ', 'Invesco'),
('J', 'Jacobs Solutions'),
('JBHT', 'J.B. Hunt'),
('JBI', 'Janus International'),
('JBL', 'Jabil'),
('JCI', 'Johnson Controls'),
('JKHY', 'Jack Henry & Associates'),
('JNJ', 'Johnson & Johnson'),
('JOBY', 'Joby Aviation'),
('JPM', 'JPMorgan Chase'),
('K', 'Kellanova'),
('KDP', 'Keurig Dr Pepper'),
('KEY', 'KeyCorp'),
('KEYS', 'Keysight Technologies'),
('KHC', 'Kraft Heinz'),
('KIM', 'Kimco Realty'),
('KODK', 'Eastman Kodak'),
('KOPN', 'Kopin Corporation'),
('KSS', 'Kohl''s'),
('KTOS', 'Kratos Defense'),
('KKR', 'KKR'),
('KLAC', 'KLA Corporation'),
('KMB', 'Kimberly-Clark'),
('KMI', 'Kinder Morgan'),
('KMX', 'CarMax'),
('KO', 'Coca-Cola Company (The)'),
('KR', 'Kroger'),
('KVUE', 'Kenvue'),
('L', 'Loews Corporation'),
('LDOS', 'Leidos'),
('LEN', 'Lennar'),
('LH', 'LabCorp'),
('LHX', 'L3Harris'),
('LII', 'Lennox International'),
('LIN', 'Linde plc'),
('LKQ', 'LKQ Corporation'),
('LLY', 'Lilly (Eli)'),
('LMT', 'Lockheed Martin'),
('LNT', 'Alliant Energy'),
('LOW', 'Lowe''s'),
('LRCX', 'Lam Research'),
('LTBR', 'Lightbridge Corporation'),
('LULU', 'Lululemon Athletica'),
('LUV', 'Southwest Airlines'),
('LVS', 'Las Vegas Sands'),
('LW', 'Lamb Weston'),
('LYB', 'LyondellBasell'),
('LYFT', 'Lyft'),
('LYV', 'Live Nation Entertainment'),
('MA', 'Mastercard'),
('MAA', 'Mid-America Apartment Communities'),
('MAPS', 'WM Technology'),
('MAR', 'Marriott International'),
('MARA', 'Marathon Digital Holdings'),
('MAS', 'Masco'),
('MCD', 'McDonald''s'),
('MCHP', 'Microchip Technology'),
('MCK', 'McKesson Corporation'),
('MCO', 'Moody''s Corporation'),
('MDLZ', 'Mondelez International'),
('MDT', 'Medtronic'),
('MET', 'MetLife'),
('META', 'Meta Platforms'),
('METC', 'Ramaco Resources'),
('MGM', 'MGM Resorts'),
('MGNI', 'Magnite'),
('MHK', 'Mohawk Industries'),
('MKC', 'McCormick & Company'),
('MKTX', 'MarketAxess'),
('MLM', 'Martin Marietta Materials'),
('MMC', 'Marsh McLennan'),
('MMM', '3M'),
('MNST', 'Monster Beverage'),
('MO', 'Altria'),
('MOH', 'Molina Healthcare'),
('MOS', 'Mosaic Company (The)'),
('MPC', 'Marathon Petroleum'),
('MPWR', 'Monolithic Power Systems'),
('MQ', 'Marqeta'),
('MRK', 'Merck & Co.'),
('MRNA', 'Moderna'),
('MS', 'Morgan Stanley'),
('MSCI', 'MSCI'),
('MSFT', 'Microsoft'),
('MSI', 'Motorola Solutions'),
('MTB', 'M&T Bank'),
('MTCH', 'Match Group'),
('MTD', 'Mettler Toledo'),
('MU', 'Micron Technology'),
('NCLH', 'Norwegian Cruise Line Holdings'),
('NDAQ', 'Nasdaq, Inc.'),
('NDSN', 'Nordson Corporation'),
('NEE', 'NextEra Energy'),
('NEM', 'Newmont'),
('NFLX', 'Netflix'),
('NEXT', 'NextDecade'),
('NG', 'NovaGold Resources'),
('NI', 'NiSource'),
('NKE', 'Nike, Inc.'),
('NN', 'NextNav'),
('NOC', 'Northrop Grumman'),
('NOW', 'ServiceNow'),
('NPKI', 'Neuropace'),
('NRG', 'NRG Energy'),
('NSC', 'Norfolk Southern Railway'),
('NTAP', 'NetApp'),
('NTRS', 'Northern Trust'),
('NUE', 'Nucor'),
('NVDA', 'Nvidia'),
('NVR', 'NVR, Inc.'),
('NWS', 'News Corp (Class B)'),
('NWSA', 'News Corp (Class A)'),
('NXPI', 'NXP Semiconductors'),
('NXT', 'Nextracker'),
('O', 'Realty Income'),
('ODFL', 'Old Dominion'),
('OKE', 'ONEOK'),
('OM', 'Outset Medical'),
('OMC', 'Omnicom Group'),
('ON', 'ON Semiconductor'),
('ORCL', 'Oracle Corporation'),
('ORLY', 'O''Reilly Auto Parts'),
('OTIS', 'Otis Worldwide'),
('OXY', 'Occidental Petroleum'),
('PANW', 'Palo Alto Networks'),
('PARA', 'Paramount Global'),
('PAYC', 'Paycom'),
('PAYX', 'Paychex'),
('PCAR', 'Paccar'),
('PBYI', 'Puma Biotechnology'),
('PCT', 'PureCycle Technologies'),
('PCG', 'PG&E Corporation'),
('PDYN', 'Palladyne AI'),
('PEG', 'Public Service Enterprise Group'),
('PEP', 'PepsiCo'),
('PGEN', 'Precigen'),
('PFE', 'Pfizer'),
('PFG', 'Principal Financial Group'),
('PG', 'Procter & Gamble'),
('PGR', 'Progressive Corporation'),
('PH', 'Parker Hannifin'),
('PHM', 'PulteGroup'),
('PINC', 'Premier Inc.'),
('PKG', 'Packaging Corporation of America'),
('PLD', 'Prologis'),
('PLTR', 'Palantir Technologies'),
('PM', 'Philip Morris International'),
('PNC', 'PNC Financial Services'),
('PNR', 'Pentair'),
('PNW', 'Pinnacle West'),
('PODD', 'Insulet Corporation'),
('PONY', 'Pony AI'),
('POOL', 'Pool Corporation'),
('PPG', 'PPG Industries'),
('PPL', 'PPL Corporation'),
('PPTA', 'Perpetua Resources'),
('PRCH', 'Porch Group'),
('PRU', 'Prudential Financial'),
('PSA', 'Public Storage'),
('PSX', 'Phillips 66'),
('PTC', 'PTC Inc.'),
('PWR', 'Quanta Services'),
('PYPL', 'PayPal'),
('QBTS', 'D-Wave Quantum'),
('QCOM', 'Qualcomm'),
('QS', 'QuantumScape'),
('QUBT', 'Quantum Computing'),
('RBLX', 'Roblox'),
('RCL', 'Royal Caribbean Group'),
('REG', 'Regency Centers'),
('REGN', 'Regeneron Pharmaceuticals'),
('RF', 'Regions Financial Corporation'),
('RGTI', 'Rigetti Computing'),
('RJF', 'Raymond James Financial'),
('RL', 'Ralph Lauren Corporation'),
('RMBS', 'Rambus'),
('RMD', 'ResMed'),
('ROK', 'Rockwell Automation'),
('ROL', 'Rollins, Inc.'),
('ROP', 'Roper Technologies'),
('ROST', 'Ross Stores'),
('RSG', 'Republic Services'),
('RTX', 'RTX Corporation'),
('RUN', 'Sunrun'),
('RVTY', 'Revvity'),
('RXST', 'RxSight'),
('SBAC', 'SBA Communications'),
('SATL', 'Satellogic'),
('SATS', 'EchoStar'),
('SBUX', 'Starbucks'),
('SCHW', 'Charles Schwab Corporation'),
('SERV', 'Serve Robotics'),
('SHAK', 'Shake Shack'),
('SHLS', 'Shoals Technologies'),
('SHW', 'Sherwin-Williams'),
('SJM', 'J.M. Smucker Company (The)'),
('SLB', 'Schlumberger'),
('SLDB', 'Solid Biosciences'),
('SMCI', 'Supermicro'),
('SMCL', 'Smurfit Kappa'),
('SMST', 'Safehold'),
('SNDL', 'SNDL Inc.'),
('SNA', 'Snap-on'),
('SNPS', 'Synopsys'),
('SO', 'Southern Company'),
('SOC', 'Sable Offshore'),
('SOFI', 'SoFi Technologies'),
('SOLV', 'Solventum'),
('SPG', 'Simon Property Group'),
('SPGI', 'S&P Global'),
('SRE', 'Sempra'),
('SRFM', 'Surf Air Mobility'),
('SSRM', 'SSR Mining'),
('STE', 'Steris'),
('STLD', 'Steel Dynamics'),
('STEM', 'Stem Inc.'),
('STNE', 'StoneCo'),
('STT', 'State Street Corporation'),
('STX', 'Seagate Technology'),
('STZ', 'Constellation Brands'),
('SW', 'Smurfit WestRock'),
('SWK', 'Stanley Black & Decker'),
('SWKS', 'Skyworks Solutions'),
('SYF', 'Synchrony Financial'),
('SYK', 'Stryker Corporation'),
('SYY', 'Sysco'),
('T', 'AT&T'),
('TAP', 'Molson Coors Beverage Company'),
('TDG', 'TransDigm Group'),
('TDY', 'Teledyne Technologies'),
('TECH', 'Bio-Techne'),
('TEL', 'TE Connectivity'),
('TER', 'Teradyne'),
('TFC', 'Truist Financial'),
('TGT', 'Target Corporation'),
('TJX', 'TJX Companies'),
('TKO', 'TKO Group Holdings'),
('TMO', 'Thermo Fisher Scientific'),
('TMUS', 'T-Mobile US'),
('TPL', 'Texas Pacific Land Corporation'),
('TPR', 'Tapestry, Inc.'),
('TRGP', 'Targa Resources'),
('TRMB', 'Trimble Inc.'),
('TRP', 'TC Energy'),
('TROW', 'T. Rowe Price'),
('TRV', 'Travelers Companies (The)'),
('TSCO', 'Tractor Supply'),
('TSLA', 'Tesla, Inc.'),
('TSLL', 'Direxion Daily TSLA Bull 2X Shares'),
('TSN', 'Tyson Foods'),
('TSSI', 'TSS Inc.'),
('TTC', 'Toro Company'),
('TT', 'Trane Technologies'),
('TTD', 'The Trade Desk'),
('TTWO', 'Take-Two Interactive'),
('TXN', 'Texas Instruments'),
('TXT', 'Textron'),
('TYL', 'Tyler Technologies'),
('UAL', 'United Airlines Holdings'),
('UBER', 'Uber'),
('UDR', 'UDR, Inc.'),
('UEC', 'Uranium Energy Corp'),
('UFPI', 'UFP Industries'),
('UHS', 'Universal Health Services'),
('ULTA', 'Ulta Beauty'),
('UMAC', 'Unusual Machines'),
('UNH', 'UnitedHealth Group'),
('UNP', 'Union Pacific Corporation'),
('UPS', 'United Parcel Service'),
('URBN', 'Urban Outfitters'),
('URI', 'United Rentals'),
('USAR', 'USA Rare Earth'),
('USB', 'U.S. Bancorp'),
('UUUU', 'Energy Fuels'),
('V', 'Visa Inc.'),
('VG', 'Vonage Holdings'),
('VICI', 'Vici Properties'),
('VLO', 'Valero Energy'),
('VLTO', 'Veralto'),
('VMC', 'Vulcan Materials Company'),
('VRSK', 'Verisk Analytics'),
('VRSN', 'Verisign'),
('VRTX', 'Vertex Pharmaceuticals'),
('VSAT', 'Viasat'),
('VSCO', 'Victoria''s Secret'),
('VST', 'Vistra Corp.'),
('VTR', 'Ventas'),
('VTLE', 'Vital Energy'),
('VTRS', 'Viatris'),
('VZ', 'Verizon'),
('WAB', 'Wabtec'),
('WAT', 'Waters Corporation'),
('WBA', 'Walgreens Boots Alliance'),
('WBD', 'Warner Bros. Discovery'),
('WDAY', 'Workday, Inc.'),
('WDC', 'Western Digital'),
('WEC', 'WEC Energy Group'),
('WELL', 'Welltower'),
('WFC', 'Wells Fargo'),
('WM', 'Waste Management'),
('WMB', 'Williams Companies'),
('WMT', 'Walmart'),
('WRB', 'W. R. Berkley Corporation'),
('WSM', 'Williams-Sonoma'),
('WST', 'West Pharmaceutical Services'),
('WTW', 'Willis Towers Watson'),
('WY', 'Weyerhaeuser'),
('WYNN', 'Wynn Resorts'),
('XEL', 'Xcel Energy'),
('XOM', 'ExxonMobil'),
('XYL', 'Xylem Inc.'),
('YEXT', 'Yext'),
('YUM', 'Yum! Brands'),
('ZBH', 'Zimmer Biomet'),
('ZBRA', 'Zebra Technologies'),
('ZTS', 'Zoetis');

-- Total: 623 symbols (S&P 500 + Additional stocks)
